Collections:
- Name: hrnetv2_udp_rhd2d
  Metadata:
    Architecture:
    - HRNetv2
    - UDP
  README: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/rhd2d/hrnetv2_udp_rhd2d.md
  Paper:
  - Deep High-Resolution Representation Learning for Visual Recognition
  - 'The Devil Is in the Details: Delving Into Unbiased Data Processing for Human
    Pose Estimation'
  - Learning to Estimate 3D Hand Pose from Single RGB Images
Models:
- Name: hrnetv2_w18_panoptic_256x256_udp
  In Collection: hrnetv2_udp_rhd2d
  Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/panoptic2d/hrnetv2_w18_panoptic_256x256_udp.py
  Metadata:
    Training Data: RHD
  Results:
  - Task: 2D Hand Pose Estimation
    Dataset: RHD
    Metrics:
      PCKh@0.7: 0.998
      AUC: 0.742
      EPE: 7.84
  Weights: https://download.openmmlab.com/mmpose/hand/udp/hrnetv2_w18_panoptic_256x256_udp-f9e15948_20210330.pth
