Collections:
- Name: hrnetv2_dark_rhd2d
  Metadata:
    Architecture:
    - HRNetv2
    - DarkPose
  README: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/rhd2d/hrnetv2_dark_rhd2d.md
  Paper:
  - Deep High-Resolution Representation Learning for Visual Recognition
  - Distribution-aware coordinate representation for human pose estimation
  - Learning to Estimate 3D Hand Pose from Single RGB Images
Models:
- Name: hrnetv2_w18_rhd2d_256x256_dark
  In Collection: hrnetv2_dark_rhd2d
  Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/rhd2d/hrnetv2_w18_rhd2d_256x256_dark.py
  Metadata:
    Training Data: RHD
  Results:
  - Task: 2D Hand Pose Estimation
    Dataset: RHD
    Metrics:
      PCK@0.2: 0.992
      AUC: 0.903
      EPE: 2.17
  Weights: https://download.openmmlab.com/mmpose/hand/dark/hrnetv2_w18_rhd2d_256x256_dark-4df3a347_20210330.pth
