Collections:
- Name: mobilenetv2_rhd2d
  Metadata:
    Architecture:
    - MobilenetV2
  README: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/rhd2d/mobilenetv2_rhd2d.md
  Paper:
  - 'Mobilenetv2: Inverted residuals and linear bottlenecks'
  - Learning to Estimate 3D Hand Pose from Single RGB Images
Models:
- Name: mobilenetv2_rhd2d_256x256
  In Collection: mobilenetv2_rhd2d
  Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/rhd2d/mobilenetv2_rhd2d_256x256.py
  Metadata:
    Training Data: RHD
  Results:
  - Task: 2D Hand Pose Estimation
    Dataset: RHD
    Metrics:
      PCK@0.2: 0.985
      AUC: 0.883
      EPE: 2.8
  Weights: https://download.openmmlab.com/mmpose/hand/mobilenetv2/mobilenetv2_rhd2d_256x256-85fa02db_20210330.pth
