Collections:
- Metadata:
    Architecture:
    - SimpleBaseline2D
    - ResNet
  Name: hand 2D Keypoint topdown_heatmap rhd2d
  Paper:
  - Title: Simple baselines for human pose estimation and tracking
    URL: http://openaccess.thecvf.com/content_ECCV_2018/html/Bin_Xiao_Simple_Baselines_for_ECCV_2018_paper.html
  - Title: Deep residual learning for image recognition
    URL: http://openaccess.thecvf.com/content_cvpr_2016/html/He_Deep_Residual_Learning_CVPR_2016_paper.html
  - Title: Learning to Estimate 3D Hand Pose from Single RGB Images
    URL: https://lmb.informatik.uni-freiburg.de/projects/hand3d/
  README: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/rhd2d/resnet_rhd2d.md
Models:
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/rhd2d/res50_rhd2d_256x256.py
  In Collection: hand 2D Keypoint topdown_heatmap rhd2d
  Metadata:
    Training Data: RHD
  Name: topdown_heatmap_res50_rhd2d_256x256
  Results:
  - Dataset: RHD
    Metrics:
      AUC: 0.898
      EPE: 2.33
      PCK@0.2: 0.991
    Task: 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/resnet/res50_rhd2d_256x256-5dc7e4cc_20210330.pth
