Collections:
- Name: LitePose
  Paper:
    Title: 'Lite pose: Efficient architecture design for 2d human pose estimation'
    URL: https://openaccess.thecvf.com/content/CVPR2022/html/Wang_Lite_Pose_Efficient_Architecture_Design_for_2D_Human_Pose_Estimation_CVPR_2022_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/backbones/litepose.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/associative_embedding/crowdpose/litepose_XS_crowdpose_256x256.py
  In Collection: LitePose
  Metadata:
    Architecture: &id001
    - Associative Embedding
    - LitePose
    Training Data: CrowdPose
  Name: associative_embedding_litepose_XS_crowdpose_256x256
  Results:
  - Dataset: CrowdPose
    Metrics:
      AP: 0.494
      AP@0.5: 0.746
      AP@0.75: 0.508
      AR: 0.555
      AR@0.5: 0.785
    Task: Body 2D Keypoint
  Weights: <>
- Config: configs/body/2d_kpt_sview_rgb_img/associative_embedding/crowdpose/litepose_S_crowdpose_448x448.py
  In Collection: LitePose
  Metadata:
    Architecture: *id001
    Training Data: CrowdPose
  Name: associative_embedding_litepose_S_crowdpose_448x448
  Results:
  - Dataset: CrowdPose
    Metrics:
      AP: 0.582
      AP@0.5: 0.817
      AP@0.75: 0.613
      AR: 0.644
      AR@0.5: 0.853
    Task: Body 2D Keypoint
  Weights: <>
