Collections:
- Name: YOLOXPose
  Paper:
    Title: 'YOLO-Pose: Enhancing YOLO for Multi Person Pose Estimation Using Object Keypoint Similarity Loss'
    URL: https://arxiv.org/abs/2204.06806
  README: https://github.com/open-mmlab/mmpose/blob/main/docs/src/papers/algorithms/yolopose.md
Models:
- Config: configs/body_2d_keypoint/yoloxpose/coco/yoloxpose_tiny_4xb64-300e_coco-416.py
  In Collection: YOLOXPose
  Metadata:
    Architecture: &id001
    - YOLOXPose
    Training Data: COCO
  Name: yoloxpose_tiny_4xb64-300e_coco-416
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.527
      AP@0.5: 0.794
      AP@0.75: 0.557
      AR: 0.577
      AR@0.5: 0.843
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/v1/body_2d_keypoint/yolox_pose/yoloxpose_tiny_4xb64-300e_coco-416-76eb44ca_20230829.pth
- Config: configs/body_2d_keypoint/yoloxpose/coco/yoloxpose_s_8xb32-300e_coco-640.py
  In Collection: YOLOXPose
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: yoloxpose_s_8xb32-300e_coco-640
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.642
      AP@0.5: 0.873
      AP@0.75: 0.702
      AR: 0.688
      AR@0.5: 0.912
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/v1/body_2d_keypoint/yolox_pose/yoloxpose_s_8xb32-300e_coco-640-56c79c1f_20230829.pth
- Config: configs/body_2d_keypoint/yoloxpose/coco/yoloxpose_m_8xb32-300e_coco-640.py
  In Collection: YOLOXPose
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: yoloxpose_m_8xb32-300e_coco-640
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.697
      AP@0.5: 0.903
      AP@0.75: 0.766
      AR: 0.739
      AR@0.5: 0.933
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/v1/body_2d_keypoint/yolox_pose/yoloxpose_m_8xb32-300e_coco-640-84e9a538_20230829.pth
- Config: configs/body_2d_keypoint/yoloxpose/coco/yoloxpose_l_8xb32-300e_coco-640.py
  In Collection: YOLOXPose
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: yoloxpose_l_8xb32-300e_coco-640
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.714
      AP@0.5: 0.906
      AP@0.75: 0.785
      AR: 0.756
      AR@0.5: 0.934
    Task: Body 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/v1/body_2d_keypoint/yolox_pose/yoloxpose_l_8xb32-300e_coco-640-de0f8dee_20230829.pth
