Collections:
- Name: hourglass_mpii
  Metadata:
    Architecture:
    - Hourglass
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/hourglass_mpii.md
  Paper:
  - Stacked hourglass networks for human pose estimation
  - '2D Human Pose Estimation: New Benchmark and State of the Art Analysis'
Models:
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--mpii--hourglass52_mpii_256x256
  In Collection: hourglass_mpii
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/hourglass52_mpii_256x256.py
  Metadata:
    Training Data: MPII
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: MPII
    Metrics: {}
  Weights: https://download.openmmlab.com/mmpose/top_down/hourglass/hourglass52_mpii_256x256-ae358435_20200812.pth
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--mpii--hourglass52_mpii_384x384
  In Collection: hourglass_mpii
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/hourglass52_mpii_384x384.py
  Metadata:
    Training Data: MPII
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: MPII
    Metrics: {}
  Weights: https://download.openmmlab.com/mmpose/top_down/hourglass/hourglass52_mpii_384x384-04090bc3_20200812.pth
