Collections:
- Metadata:
    Architecture:
    - ResNetV1D (CVPR'2019)
  Name: body 2D Keypoint topdown_heatmap mpii
  Paper:
  - Title: Bag of tricks for image classification with convolutional neural networks
    URL: http://openaccess.thecvf.com/content_CVPR_2019/html/He_Bag_of_Tricks_for_Image_Classification_with_Convolutional_Neural_Networks_CVPR_2019_paper.html
  - Title: '2D Human Pose Estimation: New Benchmark and State of the Art Analysis'
    URL: http://openaccess.thecvf.com/content_cvpr_2014/html/Andriluka_2D_Human_Pose_2014_CVPR_paper.html
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/resnetv1d_mpii.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/resnetv1d50_mpii_256x256.py
  In Collection: body 2D Keypoint topdown_heatmap mpii
  Metadata:
    Training Data: MPII (CVPR'2014)
  Name: topdown_heatmap_resnetv1d50_mpii_256x256
  Results:
  - Dataset: MPII (CVPR'2014)
    Metrics:
      Mean: 0.881
      Mean@0.1: 0.29
    Task: 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnetv1d/resnetv1d50_mpii_256x256-2337a92e_20200812.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/resnetv1d101_mpii_256x256.py
  In Collection: body 2D Keypoint topdown_heatmap mpii
  Metadata:
    Training Data: MPII (CVPR'2014)
  Name: topdown_heatmap_resnetv1d101_mpii_256x256
  Results:
  - Dataset: MPII (CVPR'2014)
    Metrics:
      Mean: 0.883
      Mean@0.1: 0.295
    Task: 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnetv1d/resnetv1d101_mpii_256x256-2851d710_20200812.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/resnetv1d152_mpii_256x256.py
  In Collection: body 2D Keypoint topdown_heatmap mpii
  Metadata:
    Training Data: MPII (CVPR'2014)
  Name: topdown_heatmap_resnetv1d152_mpii_256x256
  Results:
  - Dataset: MPII (CVPR'2014)
    Metrics:
      Mean: 0.888
      Mean@0.1: 0.3
    Task: 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnetv1d/resnetv1d152_mpii_256x256-8b10a87c_20200812.pth
