Collections:
- Name: scnet_mpii
  Metadata:
    Architecture:
    - SCNet
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/scnet_mpii.md
  Paper:
  - Improving Convolutional Networks with Self-Calibrated Convolutions
  - '2D Human Pose Estimation: New Benchmark and State of the Art Analysis'
Models:
- Name: scnet50_mpii_256x256
  In Collection: scnet_mpii
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/scnet50_mpii_256x256.py
  Metadata:
    Training Data: MPII
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: MPII
    Metrics: {}
  Weights: https://download.openmmlab.com/mmpose/top_down/scnet/scnet50_mpii_256x256-a54b6af5_20200812.pth
- Name: scnet101_mpii_256x256
  In Collection: scnet_mpii
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/scnet101_mpii_256x256.py
  Metadata:
    Training Data: MPII
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: MPII
    Metrics: {}
  Weights: https://download.openmmlab.com/mmpose/top_down/scnet/scnet101_mpii_256x256-b4c2d184_20200812.pth
