Collections:
- Name: seresnet_mpii
  Metadata:
    Architecture:
    - SEResNet
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/seresnet_mpii.md
  Paper:
  - Squeeze-and-excitation networks
  - '2D Human Pose Estimation: New Benchmark and State of the Art Analysis'
Models:
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--mpii--seresnet50_mpii_256x256
  In Collection: seresnet_mpii
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/seresnet50_mpii_256x256.py
  Metadata:
    Training Data: MPII
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: MPII
    Metrics:
      Mean: 0.884
      Mean@0.1: 0.292
  Weights: https://download.openmmlab.com/mmpose/top_down/seresnet/seresnet50_mpii_256x256-1bb21f79_20200927.pth
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--mpii--seresnet101_mpii_256x256
  In Collection: seresnet_mpii
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/seresnet101_mpii_256x256.py
  Metadata:
    Training Data: MPII
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: MPII
    Metrics:
      Mean: 0.884
      Mean@0.1: 0.295
  Weights: https://download.openmmlab.com/mmpose/top_down/seresnet/seresnet101_mpii_256x256-0ba14ff5_20200927.pth
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--mpii--seresnet152_mpii_256x256
  In Collection: seresnet_mpii
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/seresnet152_mpii_256x256.py
  Metadata:
    Training Data: MPII
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: MPII
    Metrics:
      Mean: 0.884
      Mean@0.1: 0.287
  Weights: https://download.openmmlab.com/mmpose/top_down/seresnet/seresnet152_mpii_256x256-6ea1e774_20200927.pth
