Collections:
- Name: shufflenetv2_mpii
  Metadata:
    Architecture:
    - ShufflenetV2
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/shufflenetv2_mpii.md
  Paper:
  - 'Shufflenet v2: Practical guidelines for efficient cnn architecture design'
  - '2D Human Pose Estimation: New Benchmark and State of the Art Analysis'
Models:
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--mpii--shufflenetv2_mpii_256x256
  In Collection: shufflenetv2_mpii
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/shufflenetv2_mpii_256x256.py
  Metadata:
    Training Data: MPII
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: MPII
    Metrics: {}
  Weights: https://download.openmmlab.com/mmpose/top_down/shufflenetv2/shufflenetv2_mpii_256x256-4fb9df2d_20200925.pth
