Collections:
- Metadata:
    Architecture:
    - ShufflenetV1 (CVPR'2018)
  Name: body 2D Keypoint topdown_heatmap mpii
  Paper:
  - Title: 'Shufflenet: An extremely efficient convolutional neural network for mobile
      devices'
    URL: http://openaccess.thecvf.com/content_cvpr_2018/html/Zhang_ShuffleNet_An_Extremely_CVPR_2018_paper.html
  - Title: '2D Human Pose Estimation: New Benchmark and State of the Art Analysis'
    URL: http://openaccess.thecvf.com/content_cvpr_2014/html/Andriluka_2D_Human_Pose_2014_CVPR_paper.html
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/shufflenetv1_mpii.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/shufflenetv1_mpii_256x256.py
  In Collection: body 2D Keypoint topdown_heatmap mpii
  Metadata:
    Training Data: MPII (CVPR'2014)
  Name: topdown_heatmap_shufflenetv1_mpii_256x256
  Results:
  - Dataset: MPII (CVPR'2014)
    Metrics:
      Mean: 0.823
      Mean@0.1: 0.195
    Task: 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/shufflenetv1/shufflenetv1_mpii_256x256-dcc1c896_20200925.pth
