Collections:
- Name: MTUT
  Paper:
    Title: Improving the Performance of Unimodal Dynamic Hand-Gesture Recognition With Multimodal Training
    URL: https://openaccess.thecvf.com/content_CVPR_2019/html/Abavisani_Improving_the_Performance_of_Unimodal_Dynamic_Hand-Gesture_Recognition_With_Multimodal_CVPR_2019_paper.html
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/algorithms/mtut.md
Models:
- Config: configs/gesture/gesture_sview_rgbd_vid/mtut/nvgesture/i3d_nvgesture_bbox_112x112_fps15.py
  In Collection: MTUT
  Metadata:
    Architecture: &id001
    - I3D
    Training Data: NVGesture
  Name: i3d_nvgesture_bbox_112x112_fps15
  Results:
  - Dataset: NVGesture
    Metrics:
      AP_rgb: 0.725
      AP_depth: 0.730
    Task: Gesture Recognition
  Weights: https://download.openmmlab.com/mmpose/gesture/mtut/i3d_nvgesture/i3d_nvgesture_bbox_112x112_fps15-363b5956_20220530.pth
- Config: configs/gesture/gesture_sview_rgbd_vid/mtut/nvgesture/i3d_nvgesture_bbox_224x224_fps30.py
  In Collection: MTUT
  Metadata:
    Architecture: *id001
    Training Data: NVGesture
  Name: i3d_nvgesture_bbox_224x224_fps30
  Results:
  - Dataset: NVGesture
    Metrics:
      AP_rgb: 0.782
      AP_depth: 0.811
    Task: Gesture Recognition
  Weights: https://download.openmmlab.com/mmpose/gesture/mtut/i3d_nvgesture/i3d_nvgesture_bbox_224x224_fps30-98a8f288_20220530.pth
- Config: configs/gesture/gesture_sview_rgbd_vid/mtut/nvgesture/i3d_nvgesture_224x224_fps30.py
  In Collection: MTUT
  Metadata:
    Architecture: *id001
    Training Data: NVGesture
  Name: i3d_nvgesture_224x224_fps30
  Results:
  - Dataset: NVGesture
    Metrics:
      AP_rgb: 0.739
      AP_depth: 0.809
    Task: Gesture Recognition
  Weights: https://download.openmmlab.com/mmpose/gesture/mtut/i3d_nvgesture/i3d_nvgesture_224x224_fps30-b7abf574_20220530.pth
