Collections:
- Name: cpm_jhmdb
  Metadata:
    Architecture:
    - CPM
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/jhmdb/cpm_jhmdb.md
  Paper:
  - Convolutional pose machines
  - Towards understanding action recognition
Models:
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--jhmdb--cpm_jhmdb_sub1_368x368
  In Collection: cpm_jhmdb
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/jhmdb/cpm_jhmdb_sub1_368x368.py
  Metadata:
    Training Data: JHMDB
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: JHMDB
    Metrics: {}
  Weights: https://download.openmmlab.com/mmpose/top_down/cpm/cpm_jhmdb_sub1_368x368-2d2585c9_20201122.pth
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--jhmdb--cpm_jhmdb_sub2_368x368
  In Collection: cpm_jhmdb
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/jhmdb/cpm_jhmdb_sub2_368x368.py
  Metadata:
    Training Data: JHMDB
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: JHMDB
    Metrics: {}
  Weights: https://download.openmmlab.com/mmpose/top_down/cpm/cpm_jhmdb_sub2_368x368-fc742f1f_20201122.pth
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--jhmdb--cpm_jhmdb_sub3_368x368
  In Collection: cpm_jhmdb
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/jhmdb/cpm_jhmdb_sub3_368x368.py
  Metadata:
    Training Data: JHMDB
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: JHMDB
    Metrics: {}
  Weights: https://download.openmmlab.com/mmpose/top_down/cpm/cpm_jhmdb_sub3_368x368-49337155_20201122.pth
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--jhmdb--cpm_jhmdb_sub1_368x368
  In Collection: cpm_jhmdb
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/jhmdb/cpm_jhmdb_sub1_368x368.py
  Metadata:
    Training Data: JHMDB
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: JHMDB
    Metrics: {}
  Weights: https://download.openmmlab.com/mmpose/top_down/cpm/cpm_jhmdb_sub1_368x368-2d2585c9_20201122.pth
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--jhmdb--cpm_jhmdb_sub2_368x368
  In Collection: cpm_jhmdb
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/jhmdb/cpm_jhmdb_sub2_368x368.py
  Metadata:
    Training Data: JHMDB
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: JHMDB
    Metrics: {}
  Weights: https://download.openmmlab.com/mmpose/top_down/cpm/cpm_jhmdb_sub2_368x368-fc742f1f_20201122.pth
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--jhmdb--cpm_jhmdb_sub3_368x368
  In Collection: cpm_jhmdb
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/jhmdb/cpm_jhmdb_sub3_368x368.py
  Metadata:
    Training Data: JHMDB
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: JHMDB
    Metrics: {}
  Weights: https://download.openmmlab.com/mmpose/top_down/cpm/cpm_jhmdb_sub3_368x368-49337155_20201122.pth
