Collections:
- Name: resnet_jhmdb
  Metadata:
    Architecture:
    - SimpleBaseline2D
    - ResNet
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/jhmdb/resnet_jhmdb.md
  Paper:
  - Simple baselines for human pose estimation and tracking
  - Deep residual learning for image recognition
  - Learning Delicate Local Representations for Multi-Person Pose Estimation
Models:
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--jhmdb--res50_jhmdb_sub1_256x256
  In Collection: resnet_jhmdb
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/jhmdb/res50_jhmdb_sub1_256x256.py
  Metadata:
    Training Data: RSN
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: RSN
    Metrics: {}
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res50_jhmdb_sub1_256x256-932cb3b4_20201122.pth
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--jhmdb--res50_jhmdb_sub2_256x256
  In Collection: resnet_jhmdb
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/jhmdb/res50_jhmdb_sub2_256x256.py
  Metadata:
    Training Data: RSN
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: RSN
    Metrics: {}
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res50_jhmdb_sub2_256x256-83d606f7_20201122.pth
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--jhmdb--res50_jhmdb_sub3_256x256
  In Collection: resnet_jhmdb
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/jhmdb/res50_jhmdb_sub3_256x256.py
  Metadata:
    Training Data: RSN
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: RSN
    Metrics: {}
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res50_jhmdb_sub3_256x256-c4ec1a0b_20201122.pth
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--jhmdb--res50_2deconv_jhmdb_sub1_256x256
  In Collection: resnet_jhmdb
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/jhmdb/res50_2deconv_jhmdb_sub1_256x256.py
  Metadata:
    Training Data: RSN
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: RSN
    Metrics: {}
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res50_2deconv_jhmdb_sub1_256x256-f0574a52_20201122.pth
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--jhmdb--res50_2deconv_jhmdb_sub2_256x256
  In Collection: resnet_jhmdb
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/jhmdb/res50_2deconv_jhmdb_sub2_256x256.py
  Metadata:
    Training Data: RSN
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: RSN
    Metrics: {}
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res50_2deconv_jhmdb_sub2_256x256-f63af0ff_20201122.pth
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--jhmdb--res50_2deconv_jhmdb_sub3_256x256
  In Collection: resnet_jhmdb
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/jhmdb/res50_2deconv_jhmdb_sub3_256x256.py
  Metadata:
    Training Data: RSN
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: RSN
    Metrics: {}
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res50_2deconv_jhmdb_sub3_256x256-c4bc2ddb_20201122.pth
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--jhmdb--res50_jhmdb_sub1_256x256
  In Collection: resnet_jhmdb
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/jhmdb/res50_jhmdb_sub1_256x256.py
  Metadata:
    Training Data: RSN
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: RSN
    Metrics: {}
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res50_jhmdb_sub1_256x256-932cb3b4_20201122.pth
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--jhmdb--res50_jhmdb_sub2_256x256
  In Collection: resnet_jhmdb
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/jhmdb/res50_jhmdb_sub2_256x256.py
  Metadata:
    Training Data: RSN
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: RSN
    Metrics: {}
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res50_jhmdb_sub2_256x256-83d606f7_20201122.pth
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--jhmdb--res50_jhmdb_sub3_256x256
  In Collection: resnet_jhmdb
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/jhmdb/res50_jhmdb_sub3_256x256.py
  Metadata:
    Training Data: RSN
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: RSN
    Metrics: {}
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res50_jhmdb_sub3_256x256-c4ec1a0b_20201122.pth
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--jhmdb--res50_2deconv_jhmdb_sub1_256x256
  In Collection: resnet_jhmdb
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/jhmdb/res50_2deconv_jhmdb_sub1_256x256.py
  Metadata:
    Training Data: RSN
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: RSN
    Metrics: {}
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res50_2deconv_jhmdb_sub1_256x256-f0574a52_20201122.pth
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--jhmdb--res50_2deconv_jhmdb_sub2_256x256
  In Collection: resnet_jhmdb
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/jhmdb/res50_2deconv_jhmdb_sub2_256x256.py
  Metadata:
    Training Data: RSN
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: RSN
    Metrics: {}
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res50_2deconv_jhmdb_sub2_256x256-f63af0ff_20201122.pth
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--jhmdb--res50_2deconv_jhmdb_sub3_256x256
  In Collection: resnet_jhmdb
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/jhmdb/res50_2deconv_jhmdb_sub3_256x256.py
  Metadata:
    Training Data: RSN
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: RSN
    Metrics: {}
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res50_2deconv_jhmdb_sub3_256x256-c4bc2ddb_20201122.pth
