Collections:
- Name: internet_interhand3d
  Metadata:
    Architecture:
    - InterNet
    - ResNet
  README: configs/hand/3d_kpt_sview_rgb_img/internet/interhand3d/internet_interhand3d.md
  Paper:
  - 'InterHand2.6M: A Dataset and Baseline for 3D Interacting Hand Pose Estimation
    from a Single RGB Image'
  - Deep residual learning for image recognition
  - 'InterHand2.6M: A Dataset and Baseline for 3D Interacting Hand Pose Estimation
    from a Single RGB Image'
Models:
- Name: hand--3d_kpt_sview_rgb_img--internet--interhand3d--res50_interhand3d_all_256x256
  In Collection: internet_interhand3d
  Config: configs/hand/3d_kpt_sview_rgb_img/internet/interhand3d/res50_interhand3d_all_256x256.py
  Metadata:
    Training Data: InterHand2.6M
  Results:
  - Task: 3D Hand Pose Estimation
    Dataset: InterHand2.6M
    Metrics:
      MPJPE-single: 10.16
      MPJPE-interacting: 15.27
      MPJPE-all: 12.97
      AP@h: 0.99
  Weights: https://download.openmmlab.com/mmpose/hand3d/internet/res50_intehand3d_all_256x256-b9c1cf4c_20210506.pth
- Name: hand--3d_kpt_sview_rgb_img--internet--interhand3d--res50_interhand3d_all_256x256
  In Collection: internet_interhand3d
  Config: configs/hand/3d_kpt_sview_rgb_img/internet/interhand3d/res50_interhand3d_all_256x256.py
  Metadata:
    Training Data: InterHand2.6M
  Results:
  - Task: 3D Hand Pose Estimation
    Dataset: InterHand2.6M
    Metrics:
      MPJPE-single: 12.03
      MPJPE-interacting: 17.88
      MPJPE-all: 14.84
      AP@h: 0.99
  Weights: https://download.openmmlab.com/mmpose/hand3d/internet/res50_intehand3d_all_256x256-b9c1cf4c_20210506.pth
