Collections:
- Name: ViPNAS
  Paper:
    Title: 'ViPNAS: Efficient Video Pose Estimation via Neural Architecture Search'
    URL: https://arxiv.org/abs/2105.10154
Models:
- Config: configs/wholebody/2d_kpt_sview_rgb_img/topdown_heatmap/coco-wholebody/vipnas_res50_coco_wholebody_256x192.py
  In Collection: ViPNAS
  Metadata:
    Architecture:
    - ViPNAS
    Training Data: COCO-WholeBody
  Name: topdown_heatmap_vipnas_res50_coco_wholebody_256x192
  README: configs/wholebody/2d_kpt_sview_rgb_img/topdown_heatmap/coco-wholebody/vipnas_coco-wholebody.md
  Results:
  - Dataset: COCO-WholeBody
    Metrics:
      Body AP: 0.643
      Body AR: 0.726
      Face AP: 0.587
      Face AR: 0.698
      Foot AP: 0.553
      Foot AR: 0.694
      Hand AP: 0.41
      Hand AR: 0.529
      Whole AP: 0.495
      Whole AR: 0.607
    Task: Wholebody 2D Keypoint
  Weights: https://openmmlab-share.oss-cn-hangzhou.aliyuncs.com/mmpose/top_down/vipnas/vipnas_res50_wholebody_256x192-49e1c3a4_20211112.pth
