Collections:
- Name: resnet_horse10
  Metadata:
    Architecture:
    - SimpleBaseline2D
  README: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/horse10/resnet_horse10.md
  Paper:
  - Simple baselines for human pose estimation and tracking
  - Pretraining boosts out-of-domain robustness for pose estimation
Models:
- Name: res50_horse10_256x256-split1
  In Collection: resnet_horse10
  Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/horse10/res50_horse10_256x256-split1.py
  Metadata:
    Training Data: Horse-10
  Results:
  - Task: 2D Animal Keypoint Detection
    Dataset: Horse-10
    Metrics:
      PCK@0.3: 0.956
      NME: 0.113
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res50_horse10_256x256_split1-3a3dc37e_20210405.pth
- Name: res50_horse10_256x256-split2
  In Collection: resnet_horse10
  Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/horse10/res50_horse10_256x256-split2.py
  Metadata:
    Training Data: Horse-10
  Results:
  - Task: 2D Animal Keypoint Detection
    Dataset: Horse-10
    Metrics:
      PCK@0.3: 0.954
      NME: 0.111
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res50_horse10_256x256_split2-65e2a508_20210405.pth
- Name: res50_horse10_256x256-split3
  In Collection: resnet_horse10
  Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/horse10/res50_horse10_256x256-split3.py
  Metadata:
    Training Data: Horse-10
  Results:
  - Task: 2D Animal Keypoint Detection
    Dataset: Horse-10
    Metrics:
      PCK@0.3: 0.946
      NME: 0.129
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res50_horse10_256x256_split3-9637d4eb_20210405.pth
- Name: res101_horse10_256x256-split1
  In Collection: resnet_horse10
  Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/horse10/res101_horse10_256x256-split1.py
  Metadata:
    Training Data: Horse-10
  Results:
  - Task: 2D Animal Keypoint Detection
    Dataset: Horse-10
    Metrics:
      PCK@0.3: 0.958
      NME: 0.115
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res101_horse10_256x256_split1-1b7c259c_20210405.pth
- Name: res101_horse10_256x256-split2
  In Collection: resnet_horse10
  Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/horse10/res101_horse10_256x256-split2.py
  Metadata:
    Training Data: Horse-10
  Results:
  - Task: 2D Animal Keypoint Detection
    Dataset: Horse-10
    Metrics:
      PCK@0.3: 0.955
      NME: 0.115
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res101_horse10_256x256_split2-30e2fa87_20210405.pth
- Name: res101_horse10_256x256-split3
  In Collection: resnet_horse10
  Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/horse10/res101_horse10_256x256-split3.py
  Metadata:
    Training Data: Horse-10
  Results:
  - Task: 2D Animal Keypoint Detection
    Dataset: Horse-10
    Metrics:
      PCK@0.3: 0.946
      NME: 0.126
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res101_horse10_256x256_split3-2eea5bb1_20210405.pth
- Name: res152_horse10_256x256-split1
  In Collection: resnet_horse10
  Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/horse10/res152_horse10_256x256-split1.py
  Metadata:
    Training Data: Horse-10
  Results:
  - Task: 2D Animal Keypoint Detection
    Dataset: Horse-10
    Metrics:
      PCK@0.3: 0.969
      NME: 0.105
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res152_horse10_256x256_split1-7e81fe2d_20210405.pth
- Name: res152_horse10_256x256-split2
  In Collection: resnet_horse10
  Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/horse10/res152_horse10_256x256-split2.py
  Metadata:
    Training Data: Horse-10
  Results:
  - Task: 2D Animal Keypoint Detection
    Dataset: Horse-10
    Metrics:
      PCK@0.3: 0.97
      NME: 0.103
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res152_horse10_256x256_split2-3b3404a3_20210405.pth
- Name: res152_horse10_256x256-split3
  In Collection: resnet_horse10
  Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/horse10/res152_horse10_256x256-split3.py
  Metadata:
    Training Data: Horse-10
  Results:
  - Task: 2D Animal Keypoint Detection
    Dataset: Horse-10
    Metrics:
      PCK@0.3: 0.957
      NME: 0.131
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res152_horse10_256x256_split3-c957dac5_20210405.pth
