Collections:
- Name: resnet_coco
  Metadata:
    Architecture:
    - DeepPose
    - ResNet
  README: configs/body/2d_kpt_sview_rgb_img/deeppose/coco/resnet_coco.md
  Paper:
  - 'Deeppose: Human pose estimation via deep neural networks'
  - Deep residual learning for image recognition
  - 'Microsoft coco: Common objects in context'
Models:
- Name: res50_coco_256x192
  In Collection: resnet_coco
  Config: configs/body/2d_kpt_sview_rgb_img/deeppose/coco/res50_coco_256x192.py
  Metadata:
    Training Data: COCO
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: COCO
    Metrics:
      AP: 0.526
      AP50: 0.816
      AP75: 0.586
      AR: 0.638
      AR50: 0.887
  Weights: https://download.openmmlab.com/mmpose/top_down/deeppose/deeppose_res50_coco_256x192-f6de6c0e_20210205.pth
- Name: res101_coco_256x192
  In Collection: resnet_coco
  Config: configs/body/2d_kpt_sview_rgb_img/deeppose/coco/res101_coco_256x192.py
  Metadata:
    Training Data: COCO
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: COCO
    Metrics:
      AP: 0.56
      AP50: 0.832
      AP75: 0.628
      AR: 0.668
      AR50: 0.9
  Weights: https://download.openmmlab.com/mmpose/top_down/deeppose/deeppose_res101_coco_256x192-2f247111_20210205.pth
- Name: res152_coco_256x192
  In Collection: resnet_coco
  Config: configs/body/2d_kpt_sview_rgb_img/deeppose/coco/res152_coco_256x192.py
  Metadata:
    Training Data: COCO
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: COCO
    Metrics:
      AP: 0.583
      AP50: 0.843
      AP75: 0.659
      AR: 0.686
      AR50: 0.907
  Weights: https://download.openmmlab.com/mmpose/top_down/deeppose/deeppose_res152_coco_256x192-7df89a88_20210205.pth
