Collections:
- Metadata:
    Architecture:
    - HMR (CVPR'2018)
    - ResNet (CVPR'2016)
  Name: body 3D Mesh hmr mixed
  Paper:
  - Title: End-to-end Recovery of Human Shape and Pose
    URL: http://openaccess.thecvf.com/content_cvpr_2018/html/Kanazawa_End-to-End_Recovery_of_CVPR_2018_paper.html
  - Title: Deep residual learning for image recognition
    URL: http://openaccess.thecvf.com/content_cvpr_2016/html/He_Deep_Residual_Learning_CVPR_2016_paper.html
  - Title: 'Human3.6M: Large Scale Datasets and Predictive Methods for 3D Human Sensing
      in Natural Environments'
    URL: https://ieeexplore.ieee.org/abstract/document/6682899/
  README: configs/body/3d_mesh_sview_rgb_img/hmr/mixed/resnet_mixed.md
Models:
- Config: configs/body/3d_mesh_sview_rgb_img/hmr/mixed/res50_mixed_224x224.py
  In Collection: body 3D Mesh hmr mixed
  Metadata:
    Training Data: Human3.6M (TPAMI'2014)
  Name: hmr_res50_mixed_224x224
  Results:
  - Dataset: Human3.6M (TPAMI'2014)
    Metrics:
      MPJPE (P1): 80.75
      MPJPE (P2): 80.35
      MPJPE-PA (P1): 55.08
      MPJPE-PA (P2): 52.6
    Task: 3D Mesh
  Weights: https://download.openmmlab.com/mmpose/mesh/hmr/hmr_mesh_224x224-c21e8229_20201015.pth
