Collections:
- Name: resnet_mixed
  Metadata:
    Architecture:
    - HMR
    - ResNet
  README: configs/body/3d_mesh_sview_rgb_img/hmr/mixed/resnet_mixed.md
  Paper:
  - End-to-end Recovery of Human Shape and Pose
  - Deep residual learning for image recognition
  - 'Human3.6M: Large Scale Datasets and Predictive Methods for 3D Human Sensing in
    Natural Environments'
Models:
- Name: res50_mixed_224x224
  In Collection: resnet_mixed
  Config: configs/body/3d_mesh_sview_rgb_img/hmr/res50_mixed_224x224.py
  Metadata:
    Training Data: Human3.6M
  Results:
  - Task: Human Body 3D Mesh Recovery
    Dataset: Human3.6M
    Metrics:
      MPJPE (P1): 80.75
      MPJPE-PA (P1): 55.08
      MPJPE (P2): 80.35
      MPJPE-PA (P2): 52.6
  Weights: https://download.openmmlab.com/mmpose/mesh/hmr/hmr_mesh_224x224-c21e8229_20201015.pth
