Collections:
- Name: resnet_wingloss_wflw
  Metadata:
    Architecture:
    - DeepPose
    - ResNet
    - Wingloss
  README: configs/face/2d_kpt_sview_rgb_img/deeppose/wflw/resnet_wingloss_wflw.md
  Paper:
  - 'Deeppose: Human pose estimation via deep neural networks'
  - Deep residual learning for image recognition
  - Wing Loss for Robust Facial Landmark Localisation with Convolutional Neural Networks
  - 'Look at boundary: A boundary-aware face alignment algorithm'
Models:
- Name: face--2d_kpt_sview_rgb_img--deeppose--wflw--res50_wflw_256x256_wingloss
  In Collection: resnet_wingloss_wflw
  Config: configs/face/2d_kpt_sview_rgb_img/deeppose/wflw/res50_wflw_256x256_wingloss.py
  Metadata:
    Training Data: WFLW
  Results:
  - Task: 2D Face Landmark Detection
    Dataset: WFLW
    Metrics:
      NME test: 4.64
      NME pose: 8.25
      NME illumination: 4.59
      NME occlusion: 5.56
      NME blur: 5.26
      NME makeup: 4.59
      NME expression: 5.07
  Weights: https://download.openmmlab.com/mmpose/face/deeppose/deeppose_res50_wflw_256x256_wingloss-f82a5e53_20210303.pth
