Collections:
- Name: resnet_wflw
  Metadata:
    Architecture:
    - DeepPose
    - ResNet
  README: configs/face/2d_kpt_sview_rgb_img/deeppose/wflw/resnet_wflw.md
  Paper:
  - 'Deeppose: Human pose estimation via deep neural networks'
  - Deep residual learning for image recognition
  - 'Look at boundary: A boundary-aware face alignment algorithm'
Models:
- Name: res50_wflw_256x256
  In Collection: resnet_wflw
  Config: configs/face/2d_kpt_sview_rgb_img/deeppose/wflw/res50_wflw_256x256.py
  Metadata:
    Training Data: WFLW
  Results:
  - Task: 2D Face Landmark Detection
    Dataset: WFLW
    Metrics:
      NME*test*: 4.85
      NME*pose*: 8.5
      NME*illumination*: 4.81
      NME*occlusion*: 5.69
      NME*blur*: 5.45
      NME*makeup*: 4.82
      NME*expression*: 5.2
  Weights: https://download.openmmlab.com/mmpose/face/deeppose/deeppose_res50_wflw_256x256-92d0ba7f_20210303.pth
