Collections:
- Metadata:
    Architecture:
    - HRNetv2 (TPAMI'2019)
  Name: hand 2D Keypoint topdown_heatmap coco_wholebody_hand
  Paper:
  - Title: Deep High-Resolution Representation Learning for Visual Recognition
    URL: https://ieeexplore.ieee.org/abstract/document/9052469/
  - Title: Whole-Body Human Pose Estimation in the Wild
    URL: https://link.springer.com/chapter/10.1007/978-3-030-58545-7_12
  README: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/coco_wholebody_hand/hrnetv2_coco_wholebody_hand.md
Models:
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/coco_wholebody_hand/hrnetv2_w18_coco_wholebody_hand_256x256.py
  In Collection: hand 2D Keypoint topdown_heatmap coco_wholebody_hand
  Metadata:
    Training Data: COCO-WholeBody-Hand (ECCV'2020)
  Name: topdown_heatmap_hrnetv2_w18_coco_wholebody_hand_256x256
  Results:
  - Dataset: COCO-WholeBody-Hand (ECCV'2020)
    Metrics:
      AUC: 0.84
      EPE: 4.39
      PCK@0.2: 0.813
    Task: 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/hrnetv2/hrnetv2_w18_coco_wholebody_hand_256x256-1c028db7_20210908.pth
