Collections:
- Metadata:
    Architecture:
    - SimpleBaseline2D
    - ResNet
  Name: Hand 2D Keypoint topdown_heatmap coco_wholebody_hand
  Paper:
    Title: Whole-Body Human Pose Estimation in the Wild
    URL: https://link.springer.com/chapter/10.1007/978-3-030-58545-7_12
  README: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/coco_wholebody_hand/resnet_coco_wholebody_hand.md
Models:
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/coco_wholebody_hand/res50_coco_wholebody_hand_256x256.py
  In Collection: Hand 2D Keypoint topdown_heatmap coco_wholebody_hand
  Metadata:
    Training Data: COCO-WholeBody-Hand
  Name: topdown_heatmap_res50_coco_wholebody_hand_256x256
  Results:
  - Dataset: COCO-WholeBody-Hand
    Metrics:
      AUC: 0.833
      EPE: 4.64
      PCK@0.2: 0.8
    Task: Hand 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/resnet/res50_coco_wholebody_hand_256x256-8dbc750c_20210908.pth
