Collections:
- Metadata:
    Architecture:
    - SCNet (CVPR'2020)
  Name: hand 2D Keypoint topdown_heatmap coco_wholebody_hand
  Paper:
  - Title: Improving Convolutional Networks with Self-Calibrated Convolutions
    URL: http://openaccess.thecvf.com/content_CVPR_2020/html/Liu_Improving_Convolutional_Networks_With_Self-Calibrated_Convolutions_CVPR_2020_paper.html
  - Title: Whole-Body Human Pose Estimation in the Wild
    URL: https://link.springer.com/chapter/10.1007/978-3-030-58545-7_12
  README: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/coco_wholebody_hand/scnet_coco_wholebody_hand.md
Models:
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/coco_wholebody_hand/scnet50_coco_wholebody_hand_256x256.py
  In Collection: hand 2D Keypoint topdown_heatmap coco_wholebody_hand
  Metadata:
    Training Data: COCO-WholeBody-Hand (ECCV'2020)
  Name: topdown_heatmap_scnet50_coco_wholebody_hand_256x256
  Results:
  - Dataset: COCO-WholeBody-Hand (ECCV'2020)
    Metrics:
      AUC: 0.834
      EPE: 4.55
      PCK@0.2: 0.803
    Task: 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/scnet/scnet50_coco_wholebody_hand_256x256-e73414c7_20210909.pth
