Collections:
- Metadata:
    Architecture:
    - SimpleBaseline2D (ECCV'2018)
    - ResNet (CVPR'2016)
  Name: hand 2D Keypoint topdown_heatmap freihand2d
  Paper:
  - Title: Simple baselines for human pose estimation and tracking
    URL: http://openaccess.thecvf.com/content_ECCV_2018/html/Bin_Xiao_Simple_Baselines_for_ECCV_2018_paper.html
  - Title: Deep residual learning for image recognition
    URL: http://openaccess.thecvf.com/content_cvpr_2016/html/He_Deep_Residual_Learning_CVPR_2016_paper.html
  - Title: 'Freihand: A dataset for markerless capture of hand pose and shape from
      single rgb images'
    URL: http://openaccess.thecvf.com/content_ICCV_2019/html/Zimmermann_FreiHAND_A_Dataset_for_Markerless_Capture_of_Hand_Pose_and_ICCV_2019_paper.html
  README: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/freihand2d/resnet_freihand2d.md
Models:
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/freihand2d/res50_freihand_224x224.py
  In Collection: hand 2D Keypoint topdown_heatmap freihand2d
  Metadata:
    Training Data: FreiHand (ICCV'2019)
  Name: topdown_heatmap_res50_freihand_224x224
  Results:
  - Dataset: FreiHand (ICCV'2019)
    Metrics:
      AUC: 0.868
      EPE: 3.25
      PCK@0.2: 0.993
    Task: 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/resnet/res50_freihand_224x224-ff0799bc_20200914.pth
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/freihand2d/res50_freihand_224x224.py
  In Collection: hand 2D Keypoint topdown_heatmap freihand2d
  Metadata:
    Training Data: FreiHand (ICCV'2019)
  Name: topdown_heatmap_res50_freihand_224x224
  Results:
  - Dataset: FreiHand (ICCV'2019)
    Metrics:
      AUC: 0.868
      EPE: 3.27
      PCK@0.2: 0.992
    Task: 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/resnet/res50_freihand_224x224-ff0799bc_20200914.pth
