Collections:
- Name: hrnet_posetrack18
  Metadata:
    Architecture:
    - HRNet
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/posetrack18/hrnet_posetrack18.md
  Paper:
  - Deep high-resolution representation learning for human pose estimation
  - 'Posetrack: A benchmark for human pose estimation and tracking'
Models:
- Name: hrnet_w32_posetrack18_256x192
  In Collection: hrnet_posetrack18
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/posetrack18/hrnet_w32_posetrack18_256x192.py
  Metadata:
    Training Data: PoseTrack18
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: PoseTrack18
    Metrics: {}
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_posetrack18_256x192-1ee951c4_20201028.pth
- Name: hrnet_w32_posetrack18_256x192
  In Collection: hrnet_posetrack18
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/posetrack18/hrnet_w32_posetrack18_256x192.py
  Metadata:
    Training Data: PoseTrack18
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: PoseTrack18
    Metrics: {}
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_posetrack18_256x192-1ee951c4_20201028.pth
