Collections:
- Name: resnet_posetrack18
  Metadata:
    Architecture:
    - SimpleBaseline2D
    - ResNet
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/posetrack18/resnet_posetrack18.md
  Paper:
  - Simple baselines for human pose estimation and tracking
  - Deep residual learning for image recognition
  - 'Posetrack: A benchmark for human pose estimation and tracking'
Models:
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--posetrack18--res50_posetrack18_256x192
  In Collection: resnet_posetrack18
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/posetrack18/res50_posetrack18_256x192.py
  Metadata:
    Training Data: PoseTrack18
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: PoseTrack18
    Metrics: {}
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res50_posetrack18_256x192-a62807c7_20201028.pth
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--posetrack18--res50_posetrack18_256x192
  In Collection: resnet_posetrack18
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/posetrack18/res50_posetrack18_256x192.py
  Metadata:
    Training Data: PoseTrack18
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: PoseTrack18
    Metrics: {}
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res50_posetrack18_256x192-a62807c7_20201028.pth
