Collections:
- Metadata:
    Architecture:
    - SimpleBaseline2D (ECCV'2018)
    - ResNet (CVPR'2016)
  Name: body 2D Keypoint topdown_heatmap posetrack18
  Paper:
  - Title: Simple baselines for human pose estimation and tracking
    URL: http://openaccess.thecvf.com/content_ECCV_2018/html/Bin_Xiao_Simple_Baselines_for_ECCV_2018_paper.html
  - Title: Deep residual learning for image recognition
    URL: http://openaccess.thecvf.com/content_cvpr_2016/html/He_Deep_Residual_Learning_CVPR_2016_paper.html
  - Title: 'Posetrack: A benchmark for human pose estimation and tracking'
    URL: http://openaccess.thecvf.com/content_cvpr_2018/html/Andriluka_PoseTrack_A_Benchmark_CVPR_2018_paper.html
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/posetrack18/resnet_posetrack18.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/posetrack18/res50_posetrack18_256x192.py
  In Collection: body 2D Keypoint topdown_heatmap posetrack18
  Metadata:
    Training Data: PoseTrack18 (CVPR'2018)
  Name: topdown_heatmap_res50_posetrack18_256x192
  Results:
  - Dataset: PoseTrack18 (CVPR'2018)
    Metrics:
      Ankl: 74.0
      Elb: 82.3
      Head: 86.5
      Hip: 79.9
      Knee: 78.6
      Shou: 87.5
      Total: 81.0
      Wri: 75.6
    Task: 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res50_posetrack18_256x192-a62807c7_20201028.pth
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/posetrack18/res50_posetrack18_256x192.py
  In Collection: body 2D Keypoint topdown_heatmap posetrack18
  Metadata:
    Training Data: PoseTrack18 (CVPR'2018)
  Name: topdown_heatmap_res50_posetrack18_256x192
  Results:
  - Dataset: PoseTrack18 (CVPR'2018)
    Metrics:
      Ankl: 66.4
      Elb: 77.8
      Head: 78.9
      Hip: 75.3
      Knee: 73.2
      Shou: 81.9
      Total: 75.2
      Wri: 70.8
    Task: 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res50_posetrack18_256x192-a62807c7_20201028.pth
