Collections:
- Name: hrnetv2_dark_onehand10k
  Metadata:
    Architecture:
    - HRNetv2
    - DarkPose
  README: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/onehand10k/hrnetv2_dark_onehand10k.md
  Paper:
  - Deep High-Resolution Representation Learning for Visual Recognition
  - Distribution-aware coordinate representation for human pose estimation
  - Mask-pose cascaded cnn for 2d hand pose estimation from single color image
Models:
- Name: hrnetv2_w18_onehand10k_256x256_dark
  In Collection: hrnetv2_dark_onehand10k
  Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/onehand10k/hrnetv2_w18_onehand10k_256x256_dark.py
  Metadata:
    Training Data: OneHand10K
  Results:
  - Task: 2D Hand Pose Estimation
    Dataset: OneHand10K
    Metrics:
      PCK@0.2: 0.99
      AUC: 0.573
      EPE: 23.84
  Weights: https://download.openmmlab.com/mmpose/hand/dark/hrnetv2_w18_onehand10k_256x256_dark-a2f80c64_20210330.pth
