Collections:
- Metadata:
    Architecture:
    - MobilenetV2
  Name: Hand 2D Keypoint topdown_heatmap onehand10k
  Paper:
    Title: Mask-pose cascaded cnn for 2d hand pose estimation from single color image
    URL: https://ieeexplore.ieee.org/abstract/document/8529221/
  README: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/onehand10k/mobilenetv2_onehand10k.md
Models:
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/onehand10k/mobilenetv2_onehand10k_256x256.py
  In Collection: Hand 2D Keypoint topdown_heatmap onehand10k
  Metadata:
    Training Data: OneHand10K
  Name: topdown_heatmap_mobilenetv2_onehand10k_256x256
  Results:
  - Dataset: OneHand10K
    Metrics:
      AUC: 0.537
      EPE: 28.6
      PCK@0.2: 0.986
    Task: Hand 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/mobilenetv2/mobilenetv2_onehand10k_256x256-f3a3d90e_20210330.pth
