Collections:
- Name: hrnet_animalpose
  Metadata:
    Architecture:
    - HRNet
  README: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/animalpose/hrnet_animalpose.md
  Paper:
  - Deep high-resolution representation learning for human pose estimation
  - Cross-Domain Adaptation for Animal Pose Estimation
Models:
- Name: animal--2d_kpt_sview_rgb_img--topdown_heatmap--animalpose--hrnet_w32_animalpose_256x256
  In Collection: hrnet_animalpose
  Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/animalpose/hrnet_w32_animalpose_256x256.py
  Metadata:
    Training Data: Animal-Pose
  Results:
  - Task: 2D Animal Keypoint Detection
    Dataset: Animal-Pose
    Metrics:
      AP: 0.736
      AP50: 0.959
      AP75: 0.832
      AR: 0.775
      AR50: 0.966
  Weights: https://download.openmmlab.com/mmpose/animal/hrnet/hrnet_w32_animalpose_256x256-1aa7f075_20210426.pth
- Name: animal--2d_kpt_sview_rgb_img--topdown_heatmap--animalpose--hrnet_w48_animalpose_256x256
  In Collection: hrnet_animalpose
  Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/animalpose/hrnet_w48_animalpose_256x256.py
  Metadata:
    Training Data: Animal-Pose
  Results:
  - Task: 2D Animal Keypoint Detection
    Dataset: Animal-Pose
    Metrics:
      AP: 0.737
      AP50: 0.959
      AP75: 0.823
      AR: 0.778
      AR50: 0.962
  Weights: https://download.openmmlab.com/mmpose/animal/hrnet/hrnet_w48_animalpose_256x256-34644726_20210426.pth
