Collections:
- Name: resnet_animalpose
  Metadata:
    Architecture:
    - SimpleBaseline2D
  README: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/animalpose/resnet_animalpose.md
  Paper:
  - Simple baselines for human pose estimation and tracking
  - Cross-Domain Adaptation for Animal Pose Estimation
Models:
- Name: animal--2d_kpt_sview_rgb_img--topdown_heatmap--animalpose--res50_animalpose_256x256
  In Collection: resnet_animalpose
  Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/animalpose/res50_animalpose_256x256.py
  Metadata:
    Training Data: Animal-Pose
  Results:
  - Task: 2D Animal Keypoint Detection
    Dataset: Animal-Pose
    Metrics:
      AP: 0.688
      AP@50: 0.945
      AP@75: 0.772
      AR: 0.733
      AR@50: 0.952
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res50_animalpose_256x256-e1f30bff_20210426.pth
- Name: animal--2d_kpt_sview_rgb_img--topdown_heatmap--animalpose--res101_animalpose_256x256
  In Collection: resnet_animalpose
  Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/animalpose/res101_animalpose_256x256.py
  Metadata:
    Training Data: Animal-Pose
  Results:
  - Task: 2D Animal Keypoint Detection
    Dataset: Animal-Pose
    Metrics:
      AP: 0.696
      AP@50: 0.948
      AP@75: 0.785
      AR: 0.737
      AR@50: 0.954
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res101_animalpose_256x256-85563f4a_20210426.pth
- Name: animal--2d_kpt_sview_rgb_img--topdown_heatmap--animalpose--res152_animalpose_256x256
  In Collection: resnet_animalpose
  Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/animalpose/res152_animalpose_256x256.py
  Metadata:
    Training Data: Animal-Pose
  Results:
  - Task: 2D Animal Keypoint Detection
    Dataset: Animal-Pose
    Metrics:
      AP: 0.709
      AP@50: 0.948
      AP@75: 0.797
      AR: 0.749
      AR@50: 0.951
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res152_animalpose_256x256-a0a7506c_20210426.pth
