Collections:
- Metadata:
    Architecture:
    - HRNet (CVPR'2019)
  Name: body 2D Keypoint topdown_heatmap crowdpose
  Paper:
  - Title: Deep high-resolution representation learning for human pose estimation
    URL: http://openaccess.thecvf.com/content_CVPR_2019/html/Sun_Deep_High-Resolution_Representation_Learning_for_Human_Pose_Estimation_CVPR_2019_paper.html
  - Title: 'CrowdPose: Efficient Crowded Scenes Pose Estimation and A New Benchmark'
    URL: http://openaccess.thecvf.com/content_CVPR_2019/html/Li_CrowdPose_Efficient_Crowded_Scenes_Pose_Estimation_and_a_New_Benchmark_CVPR_2019_paper.html
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/crowdpose/hrnet_crowdpose.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/crowdpose/hrnet_w32_crowdpose_256x192.py
  In Collection: body 2D Keypoint topdown_heatmap crowdpose
  Metadata:
    Training Data: CrowdPose (CVPR'2019)
  Name: topdown_heatmap_hrnet_w32_crowdpose_256x192
  Results:
  - Dataset: CrowdPose (CVPR'2019)
    Metrics:
      AP: 0.675
      AP (E): 0.77
      AP (H): 0.553
      AP (M): 0.687
      AP@0.5: 0.825
      AP@0.75: 0.729
    Task: 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_crowdpose_256x192-960be101_20201227.pth
