Collections:
- Name: hrnet_crowdpose
  Metadata:
    Architecture:
    - HRNet
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/crowdpose/hrnet_crowdpose.md
  Paper:
  - Deep high-resolution representation learning for human pose estimation
  - 'CrowdPose: Efficient Crowded Scenes Pose Estimation and A New Benchmark'
Models:
- Name: hrnet_w32_crowdpose_256x192
  In Collection: hrnet_crowdpose
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/crowdpose/hrnet_w32_crowdpose_256x192.py
  Metadata:
    Training Data: CrowdPose
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: CrowdPose
    Metrics:
      AP: 0.675
      AP50: 0.825
      AP75: 0.729
      AP (E): 0.77
      AP (M): 0.687
      AP (H): 0.553
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_crowdpose_256x192-960be101_20201227.pth
