Collections:
- Name: hrnetv2_dark_aflw
  Metadata:
    Architecture:
    - HRNetv2
    - DarkPose
  README: configs/face/2d_kpt_sview_rgb_img/topdown_heatmap/aflw/hrnetv2_dark_aflw.md
  Paper:
  - Deep High-Resolution Representation Learning for Visual Recognition
  - Distribution-aware coordinate representation for human pose estimation
  - 'Annotated facial landmarks in the wild: A large-scale, real-world database for
    facial landmark localization'
Models:
- Name: hrnetv2_w18_aflw_256x256_dark
  In Collection: hrnetv2_dark_aflw
  Config: configs/face/2d_kpt_sview_rgb_img/topdown_heatmap/aflw/hrnetv2_w18_aflw_256x256_dark.py
  Metadata:
    Training Data: AFLW
  Results:
  - Task: 2D Face Landmark Detection
    Dataset: AFLW
    Metrics:
      NME*full*: 1.41
      NME*frontal*: 1.27
  Weights: https://download.openmmlab.com/mmpose/face/darkpose/hrnetv2_w18_aflw_256x256_dark-219606c0_20210125.pth
