Collections:
- Metadata:
    Architecture:
    - HRNetv2
  Name: face 2D Keypoint topdown_heatmap aflw
  Paper:
  - Title: Deep High-Resolution Representation Learning for Visual Recognition
    URL: https://ieeexplore.ieee.org/abstract/document/9052469/
  - Title: 'Annotated facial landmarks in the wild: A large-scale, real-world database
      for facial landmark localization'
    URL: https://ieeexplore.ieee.org/abstract/document/6130513/
  README: configs/face/2d_kpt_sview_rgb_img/topdown_heatmap/aflw/hrnetv2_aflw.md
Models:
- Config: configs/face/2d_kpt_sview_rgb_img/topdown_heatmap/aflw/hrnetv2_w18_aflw_256x256.py
  In Collection: face 2D Keypoint topdown_heatmap aflw
  Metadata:
    Training Data: AFLW
  Name: topdown_heatmap_hrnetv2_w18_aflw_256x256
  Results:
  - Dataset: AFLW
    Metrics:
      NME frontal: 1.27
      NME full: 1.41
    Task: 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/face/hrnetv2/hrnetv2_w18_aflw_256x256-f2bbc62b_20210125.pth
