Collections:
- Name: hrnetv2_aflw
  Metadata:
    Architecture:
    - HRNetv2
  README: configs/face/2d_kpt_sview_rgb_img/topdown_heatmap/aflw/hrnetv2_aflw.md
  Paper:
  - Deep High-Resolution Representation Learning for Visual Recognition
  - 'Annotated facial landmarks in the wild: A large-scale, real-world database for
    facial landmark localization'
Models:
- Name: hrnetv2_w18_aflw_256x256
  In Collection: hrnetv2_aflw
  Config: configs/face/2d_kpt_sview_rgb_img/topdown_heatmap/aflw/hrnetv2_w18_aflw_256x256.py
  Metadata:
    Training Data: AFLW
  Results:
  - Task: 2D Face Landmark Detection
    Dataset: AFLW
    Metrics:
      NME*full*: 1.41
      NME*frontal*: 1.27
  Weights: https://download.openmmlab.com/mmpose/face/hrnetv2/hrnetv2_w18_aflw_256x256-f2bbc62b_20210125.pth
