Collections:
- Name: hrnetv2_dark_wflw
  Metadata:
    Architecture:
    - HRNetv2
    - DarkPose
  README: configs/face/2d_kpt_sview_rgb_img/topdown_heatmap/wflw/hrnetv2_dark_wflw.md
  Paper:
  - Deep High-Resolution Representation Learning for Visual Recognition
  - Distribution-aware coordinate representation for human pose estimation
  - 'Look at boundary: A boundary-aware face alignment algorithm'
Models:
- Name: hrnetv2_w18_wflw_256x256_dark
  In Collection: hrnetv2_dark_wflw
  Config: configs/face/2d_kpt_sview_rgb_img/topdown_heatmap/wflw/hrnetv2_w18_wflw_256x256_dark.py
  Metadata:
    Training Data: WFLW
  Results:
  - Task: 2D Face Landmark Detection
    Dataset: WFLW
    Metrics:
      NME test: 3.98
      NME pose: 6.99
      NME illumination: 3.96
      NME occlusion: 4.78
      NME blur: 4.57
      NME makeup: 3.87
      NME expression: 4.3
  Weights: https://download.openmmlab.com/mmpose/face/darkpose/hrnetv2_w18_wflw_256x256_dark-3f8e0c2c_20210125.pth
