Collections:
- Metadata:
    Architecture:
    - DeepPose
    - ResNet
  Name: Hand 2D Keypoint deeppose rhd2d
  Paper:
    Title: Learning to Estimate 3D Hand Pose from Single RGB Images
    URL: https://lmb.informatik.uni-freiburg.de/projects/hand3d/
  README: configs/hand/2d_kpt_sview_rgb_img/deeppose/rhd2d/resnet_rhd2d.md
Models:
- Config: configs/hand/2d_kpt_sview_rgb_img/deeppose/rhd2d/res50_rhd2d_256x256.py
  In Collection: Hand 2D Keypoint deeppose rhd2d
  Metadata:
    Training Data: RHD
  Name: deeppose_res50_rhd2d_256x256
  Results:
  - Dataset: RHD
    Metrics:
      AUC: 0.865
      EPE: 3.29
      PCK@0.2: 0.988
    Task: Hand 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/deeppose/deeppose_res50_rhd2d_256x256-37f1c4d3_20210330.pth
