Collections:
- Name: resnet_rhd2d
  Metadata:
    Architecture:
    - DeepPose
    - ResNet
  README: configs/hand/2d_kpt_sview_rgb_img/deeppose/rhd2d/resnet_rhd2d.md
  Paper:
  - 'Deeppose: Human pose estimation via deep neural networks'
  - Deep residual learning for image recognition
  - Learning to Estimate 3D Hand Pose from Single RGB Images
Models:
- Name: res50_rhd2d_256x256
  In Collection: resnet_rhd2d
  Config: configs/hand/2d_kpt_sview_rgb_img/deeppose/rhd2d/res50_rhd2d_256x256.py
  Metadata:
    Training Data: RHD
  Results:
  - Task: 2D Hand Pose Estimation
    Dataset: RHD
    Metrics:
      PCK@0.2: 0.988
      AUC: 0.865
      EPE: 3.29
  Weights: https://download.openmmlab.com/mmpose/hand/deeppose/deeppose_res50_rhd2d_256x256-37f1c4d3_20210330.pth
