Collections:
- Name: resnet_deepfashion
  Metadata:
    Architecture:
    - SimpleBaseline2D
    - ResNet
  README: configs/fashion/2d_kpt_sview_rgb_img/topdown_heatmap/deepfashion/resnet_deepfashion.md
  Paper:
  - Simple baselines for human pose estimation and tracking
  - Deep residual learning for image recognition
  - 'DeepFashion: Powering Robust Clothes Recognition and Retrieval with Rich Annotations'
  - Fashion Landmark Detection in the Wild
Models:
- Name: res50_deepfashion_upper_256x192
  In Collection: resnet_deepfashion
  Config: configs/fashion/2d_kpt_sview_rgb_img/topdown_heatmap/deepfashion/res50_deepfashion_upper_256x192.py
  Metadata:
    Training Data: DeepFashion
  Results:
  - Task: 2D Fashion Landmark Detection
    Dataset: DeepFashion
    Metrics:
      PCK@0.2: 0.954
      AUC: 0.578
      EPE: 16.8
  Weights: https://download.openmmlab.com/mmpose/fashion/resnet/res50_deepfashion_upper_256x192-41794f03_20210124.pth
- Name: res50_deepfashion_lower_256x192
  In Collection: resnet_deepfashion
  Config: configs/fashion/2d_kpt_sview_rgb_img/topdown_heatmap/deepfashion/res50_deepfashion_lower_256x192.py
  Metadata:
    Training Data: DeepFashion
  Results:
  - Task: 2D Fashion Landmark Detection
    Dataset: DeepFashion
    Metrics:
      PCK@0.2: 0.965
      AUC: 0.744
      EPE: 10.5
  Weights: https://download.openmmlab.com/mmpose/fashion/resnet/res50_deepfashion_lower_256x192-1292a839_20210124.pth
- Name: res50_deepfashion_full_256x192
  In Collection: resnet_deepfashion
  Config: configs/fashion/2d_kpt_sview_rgb_img/topdown_heatmap/deepfashion/res50_deepfashion_full_256x192.py
  Metadata:
    Training Data: DeepFashion
  Results:
  - Task: 2D Fashion Landmark Detection
    Dataset: DeepFashion
    Metrics:
      PCK@0.2: 0.977
      AUC: 0.664
      EPE: 12.7
  Weights: https://download.openmmlab.com/mmpose/fashion/resnet/res50_deepfashion_full_256x192-0dbd6e42_20210124.pth
