Collections:
- Name: DEKR
  Paper:
    Title: Bottom-up human pose estimation via disentangled keypoint regression
    URL: https://arxiv.org/abs/2104.02300
  README: https://github.com/open-mmlab/mmpose/blob/master/docs/en/papers/algorithms/dekr.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/disentangled_keypoint_regression/coco/hrnet_w32_coco_512x512_dekr.py
  In Collection: DEKR
  Metadata:
    Architecture: &id001
    - DEKR
    - HRNet
    Training Data: COCO
  Name: disentangled_keypoint_regression_hrnet_w32_coco_512x512_dekr
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.68
      AP@0.5: 0.867
      AP@0.75: 0.748
      AR: 0.729
      AR@0.5: 0.896
    Task: Body 2D Keypoint
  Weights: <>
- Config: configs/body/2d_kpt_sview_rgb_img/disentangled_keypoint_regression/coco/hrnet_w48_coco_640x640_dekr.py
  In Collection: DEKR
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: disentangled_keypoint_regression_hrnet_w48_coco_640x640_dekr
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.707
      AP@0.5: 0.875
      AP@0.75: 0.771
      AR: 0.759
      AR@0.5: 0.91
    Task: Body 2D Keypoint
  Weights: <>
- Config: configs/body/2d_kpt_sview_rgb_img/disentangled_keypoint_regression/coco/hrnet_w32_coco_512x512_dekr_multiscale.py
  In Collection: DEKR
  Metadata:
    Architecture: *id001
    Training Data: COCO
  Name: disentangled_keypoint_regression_hrnet_w32_coco_512x512_dekr_multiscale
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.704
      AP@0.5: 0.875
      AP@0.75: 0.769
      AR: 0.756
      AR@0.5: 0.914
    Task: Body 2D Keypoint
  Weights: <>
