Collections:
- Name: hrnetv2_300w
  Metadata:
    Architecture:
    - HRNetv2
  README: configs/face/2d_kpt_sview_rgb_img/topdown_heatmap/300w/hrnetv2_300w.md
  Paper:
  - Deep High-Resolution Representation Learning for Visual Recognition
  - '300 faces in-the-wild challenge: Database and results'
Models: []
