Collections:
- Name: resnet_onehand10k
  Metadata:
    Architecture:
    - DeepPose
    - ResNet
  README: configs/hand/2d_kpt_sview_rgb_img/deeppose/onehand10k/resnet_onehand10k.md
  Paper:
  - 'Deeppose: Human pose estimation via deep neural networks'
  - Deep residual learning for image recognition
  - Mask-pose cascaded cnn for 2d hand pose estimation from single color image
Models:
- Name: res50_onehand10k_256x256
  In Collection: resnet_onehand10k
  Config: configs/hand/2d_kpt_sview_rgb_img/deeppose/onehand10k/res50_onehand10k_256x256.py
  Metadata:
    Training Data: OneHand10K
  Results:
  - Task: 2D Hand Pose Estimation
    Dataset: OneHand10K
    Metrics:
      PCK@0.2: 0.99
      AUC: 0.486
      EPE: 34.28
  Weights: https://download.openmmlab.com/mmpose/hand/deeppose/deeppose_res50_onehand10k_256x256-cbddf43a_20210330.pth
