Collections:
- Metadata:
    Architecture:
    - Associative Embedding
    - HigherHRNet
  Name: body 2D Keypoint associative_embedding coco
  Paper:
  - Title: 'Associative embedding: End-to-end learning for joint detection and grouping'
    URL: https://arxiv.org/abs/1611.05424
  - Title: 'HigherHRNet: Scale-Aware Representation Learning for Bottom-Up Human Pose
      Estimation'
    URL: http://openaccess.thecvf.com/content_CVPR_2020/html/Cheng_HigherHRNet_Scale-Aware_Representation_Learning_for_Bottom-Up_Human_Pose_Estimation_CVPR_2020_paper.html
  - Title: 'Microsoft coco: Common objects in context'
    URL: https://link.springer.com/chapter/10.1007/978-3-319-10602-1_48
  README: configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco/higherhrnet_coco.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco/higherhrnet_w32_coco_512x512.py
  In Collection: body 2D Keypoint associative_embedding coco
  Metadata:
    Training Data: COCO
  Name: associative_embedding_higherhrnet_w32_coco_512x512
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.677
      AP@0.5: 0.87
      AP@0.75: 0.738
      AR: 0.723
      AR@0.5: 0.89
    Task: 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/bottom_up/higher_hrnet32_coco_512x512-8ae85183_20200713.pth
- Config: configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco/higherhrnet_w32_coco_640x640.py
  In Collection: body 2D Keypoint associative_embedding coco
  Metadata:
    Training Data: COCO
  Name: associative_embedding_higherhrnet_w32_coco_640x640
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.686
      AP@0.5: 0.871
      AP@0.75: 0.747
      AR: 0.733
      AR@0.5: 0.898
    Task: 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/bottom_up/higher_hrnet32_coco_640x640-a22fe938_20200712.pth
- Config: configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco/higherhrnet_w48_coco_512x512.py
  In Collection: body 2D Keypoint associative_embedding coco
  Metadata:
    Training Data: COCO
  Name: associative_embedding_higherhrnet_w48_coco_512x512
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.686
      AP@0.5: 0.873
      AP@0.75: 0.741
      AR: 0.731
      AR@0.5: 0.892
    Task: 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/bottom_up/higher_hrnet48_coco_512x512-60fedcbc_20200712.pth
- Config: configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco/higherhrnet_w32_coco_512x512.py
  In Collection: body 2D Keypoint associative_embedding coco
  Metadata:
    Training Data: COCO
  Name: associative_embedding_higherhrnet_w32_coco_512x512
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.706
      AP@0.5: 0.881
      AP@0.75: 0.771
      AR: 0.747
      AR@0.5: 0.901
    Task: 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/bottom_up/higher_hrnet32_coco_512x512-8ae85183_20200713.pth
- Config: configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco/higherhrnet_w32_coco_640x640.py
  In Collection: body 2D Keypoint associative_embedding coco
  Metadata:
    Training Data: COCO
  Name: associative_embedding_higherhrnet_w32_coco_640x640
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.706
      AP@0.5: 0.88
      AP@0.75: 0.77
      AR: 0.749
      AR@0.5: 0.902
    Task: 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/bottom_up/higher_hrnet32_coco_640x640-a22fe938_20200712.pth
- Config: configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco/higherhrnet_w48_coco_512x512.py
  In Collection: body 2D Keypoint associative_embedding coco
  Metadata:
    Training Data: COCO
  Name: associative_embedding_higherhrnet_w48_coco_512x512
  Results:
  - Dataset: COCO
    Metrics:
      AP: 0.716
      AP@0.5: 0.884
      AP@0.75: 0.775
      AR: 0.755
      AR@0.5: 0.901
    Task: 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/bottom_up/higher_hrnet48_coco_512x512-60fedcbc_20200712.pth
