Collections:
- Name: hrnet_udp_coco
  Metadata:
    Architecture:
    - Associative Embedding
    - HRNet
    - UDP
  README: configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco/hrnet_udp_coco.md
  Paper:
  - 'Associative embedding: End-to-end learning for joint detection and grouping'
  - Deep high-resolution representation learning for human pose estimation
  - 'The Devil Is in the Details: Delving Into Unbiased Data Processing for Human
    Pose Estimation'
  - 'Microsoft coco: Common objects in context'
Models:
- Name: body--2d_kpt_sview_rgb_img--associative_embedding--coco--hrnet_w32_coco_512x512_udp
  In Collection: hrnet_udp_coco
  Config: configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco/hrnet_w32_coco_512x512_udp.py
  Metadata:
    Training Data: COCO
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: COCO
    Metrics:
      AP: 0.671
      AP@0.5: 0.863
      AP@0.75: 0.729
      AR: 0.717
      AR@0.5: 0.889
  Weights: https://download.openmmlab.com/mmpose/bottom_up/hrnet_w32_coco_512x512_udp-91663bf9_20210220.pth
- Name: body--2d_kpt_sview_rgb_img--associative_embedding--coco--hrnet_w48_coco_512x512_udp
  In Collection: hrnet_udp_coco
  Config: configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco/hrnet_w48_coco_512x512_udp.py
  Metadata:
    Training Data: COCO
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: COCO
    Metrics:
      AP: 0.681
      AP@0.5: 0.872
      AP@0.75: 0.741
      AR: 0.725
      AR@0.5: 0.892
  Weights: https://download.openmmlab.com/mmpose/bottom_up/hrnet_w48_coco_512x512_udp-de08fd8c_20210222.pth
