Collections:
- Name: resnet_coco
  Metadata:
    Architecture:
    - Associative Embedding
    - ResNet
  README: configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco/resnet_coco.md
  Paper:
  - 'Associative embedding: End-to-end learning for joint detection and grouping'
  - Deep residual learning for image recognition
  - 'Microsoft coco: Common objects in context'
Models:
- Name: body--2d_kpt_sview_rgb_img--associative_embedding--coco--res50_coco_512x512
  In Collection: resnet_coco
  Config: configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco/res50_coco_512x512.py
  Metadata:
    Training Data: COCO
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: COCO
    Metrics:
      AP: 0.466
      AP@50: 0.742
      AP@75: 0.479
      AR: 0.552
      AR@50: 0.797
  Weights: https://download.openmmlab.com/mmpose/bottom_up/res50_coco_512x512-5521bead_20200816.pth
- Name: body--2d_kpt_sview_rgb_img--associative_embedding--coco--res50_coco_640x640
  In Collection: resnet_coco
  Config: configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco/res50_coco_640x640.py
  Metadata:
    Training Data: COCO
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: COCO
    Metrics:
      AP: 0.479
      AP@50: 0.757
      AP@75: 0.487
      AR: 0.566
      AR@50: 0.81
  Weights: https://download.openmmlab.com/mmpose/bottom_up/res50_coco_640x640-2046f9cb_20200822.pth
- Name: body--2d_kpt_sview_rgb_img--associative_embedding--coco--res101_coco_512x512
  In Collection: resnet_coco
  Config: configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco/res101_coco_512x512.py
  Metadata:
    Training Data: COCO
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: COCO
    Metrics:
      AP: 0.554
      AP@50: 0.807
      AP@75: 0.599
      AR: 0.622
      AR@50: 0.841
  Weights: https://download.openmmlab.com/mmpose/bottom_up/res101_coco_512x512-e0c95157_20200816.pth
- Name: body--2d_kpt_sview_rgb_img--associative_embedding--coco--res152_coco_512x512
  In Collection: resnet_coco
  Config: configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco/res152_coco_512x512.py
  Metadata:
    Training Data: COCO
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: COCO
    Metrics:
      AP: 0.595
      AP@50: 0.829
      AP@75: 0.648
      AR: 0.651
      AR@50: 0.856
  Weights: https://download.openmmlab.com/mmpose/bottom_up/res152_coco_512x512-364eb38d_20200822.pth
- Name: body--2d_kpt_sview_rgb_img--associative_embedding--coco--res50_coco_512x512
  In Collection: resnet_coco
  Config: configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco/res50_coco_512x512.py
  Metadata:
    Training Data: COCO
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: COCO
    Metrics:
      AP: 0.503
      AP@50: 0.765
      AP@75: 0.521
      AR: 0.591
      AR@50: 0.821
  Weights: https://download.openmmlab.com/mmpose/bottom_up/res50_coco_512x512-5521bead_20200816.pth
- Name: body--2d_kpt_sview_rgb_img--associative_embedding--coco--res50_coco_640x640
  In Collection: resnet_coco
  Config: configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco/res50_coco_640x640.py
  Metadata:
    Training Data: COCO
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: COCO
    Metrics:
      AP: 0.525
      AP@50: 0.784
      AP@75: 0.542
      AR: 0.61
      AR@50: 0.832
  Weights: https://download.openmmlab.com/mmpose/bottom_up/res50_coco_640x640-2046f9cb_20200822.pth
- Name: body--2d_kpt_sview_rgb_img--associative_embedding--coco--res101_coco_512x512
  In Collection: resnet_coco
  Config: configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco/res101_coco_512x512.py
  Metadata:
    Training Data: COCO
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: COCO
    Metrics:
      AP: 0.603
      AP@50: 0.831
      AP@75: 0.641
      AR: 0.668
      AR@50: 0.87
  Weights: https://download.openmmlab.com/mmpose/bottom_up/res101_coco_512x512-e0c95157_20200816.pth
- Name: body--2d_kpt_sview_rgb_img--associative_embedding--coco--res152_coco_512x512
  In Collection: resnet_coco
  Config: configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco/res152_coco_512x512.py
  Metadata:
    Training Data: COCO
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: COCO
    Metrics:
      AP: 0.66
      AP@50: 0.86
      AP@75: 0.713
      AR: 0.709
      AR@50: 0.889
  Weights: https://download.openmmlab.com/mmpose/bottom_up/res152_coco_512x512-364eb38d_20200822.pth
