Collections:
- Metadata:
    Architecture:
    - HRNetv2
  Name: Face 2D Keypoint topdown_heatmap coco_wholebody_face
  Paper:
    Title: Whole-Body Human Pose Estimation in the Wild
    URL: https://link.springer.com/chapter/10.1007/978-3-030-58545-7_12
  README: configs/face/2d_kpt_sview_rgb_img/topdown_heatmap/coco_wholebody_face/hrnetv2_coco_wholebody_face.md
Models:
- Config: configs/face/2d_kpt_sview_rgb_img/topdown_heatmap/coco_wholebody_face/hrnetv2_w18_coco_wholebody_face_256x256.py
  In Collection: Face 2D Keypoint topdown_heatmap coco_wholebody_face
  Metadata:
    Training Data: COCO-WholeBody-Face
  Name: topdown_heatmap_hrnetv2_w18_coco_wholebody_face_256x256
  Results:
  - Dataset: COCO-WholeBody-Face
    Metrics:
      NME: 0.0569
    Task: Face 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/face/hrnetv2/hrnetv2_w18_coco_wholebody_face_256x256-c1ca469b_20210909.pth
