Collections:
- Metadata:
    Architecture:
    - SCNet (CVPR'2020)
  Name: face 2D Keypoint topdown_heatmap coco_wholebody_face
  Paper:
  - Title: Improving Convolutional Networks with Self-Calibrated Convolutions
    URL: http://openaccess.thecvf.com/content_CVPR_2020/html/Liu_Improving_Convolutional_Networks_With_Self-Calibrated_Convolutions_CVPR_2020_paper.html
  - Title: Whole-Body Human Pose Estimation in the Wild
    URL: https://link.springer.com/chapter/10.1007/978-3-030-58545-7_12
  README: configs/face/2d_kpt_sview_rgb_img/topdown_heatmap/coco_wholebody_face/scnet_coco_wholebody_face.md
Models:
- Config: configs/face/2d_kpt_sview_rgb_img/topdown_heatmap/coco_wholebody_face/scnet50_coco_wholebody_face_256x256.py
  In Collection: face 2D Keypoint topdown_heatmap coco_wholebody_face
  Metadata:
    Training Data: COCO-WholeBody-Face (ECCV'2020)
  Name: topdown_heatmap_scnet50_coco_wholebody_face_256x256
  Results:
  - Dataset: COCO-WholeBody-Face (ECCV'2020)
    Metrics:
      NME: 0.0565
    Task: 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/face/scnet/scnet50_coco_wholebody_face_256x256-a0183f5f_20210909.pth
