Collections:
- Name: hrnet_atrw
  Metadata:
    Architecture:
    - HRNet
  README: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/atrw/hrnet_atrw.md
  Paper:
  - Deep high-resolution representation learning for human pose estimation
  - 'ATRW: A Benchmark for Amur Tiger Re-identification in the Wild'
Models:
- Name: hrnet_w32_atrw_256x256
  In Collection: hrnet_atrw
  Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/atrw/hrnet_w32_atrw_256x256.py
  Metadata:
    Training Data: ATRW
  Results:
  - Task: 2D Animal Keypoint Detection
    Dataset: ATRW
    Metrics:
      AP: 0.912
      AP50: 0.973
      AP75: 0.959
      AR: 0.938
      AR50: 0.985
  Weights: https://download.openmmlab.com/mmpose/animal/hrnet/hrnet_w32_atrw_256x256-f027f09a_20210414.pth
- Name: hrnet_w48_atrw_256x256
  In Collection: hrnet_atrw
  Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/atrw/hrnet_w48_atrw_256x256.py
  Metadata:
    Training Data: ATRW
  Results:
  - Task: 2D Animal Keypoint Detection
    Dataset: ATRW
    Metrics:
      AP: 0.911
      AP50: 0.972
      AP75: 0.946
      AR: 0.937
      AR50: 0.985
  Weights: https://download.openmmlab.com/mmpose/animal/hrnet/hrnet_w48_atrw_256x256-ac088892_20210414.pth
