Collections:
- Name: resnet_atrw
  Metadata:
    Architecture:
    - SimpleBaseline2D
  README: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/atrw/resnet_atrw.md
  Paper:
  - Simple baselines for human pose estimation and tracking
  - 'ATRW: A Benchmark for Amur Tiger Re-identification in the Wild'
Models:
- Name: animal--2d_kpt_sview_rgb_img--topdown_heatmap--atrw--res50_atrw_256x256
  In Collection: resnet_atrw
  Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/atrw/res50_atrw_256x256.py
  Metadata:
    Training Data: ATRW
  Results:
  - Task: 2D Animal Keypoint Detection
    Dataset: ATRW
    Metrics:
      AP: 0.9
      AP50: 0.973
      AP75: 0.932
      AR: 0.929
      AR50: 0.985
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res50_atrw_256x256-546c4594_20210414.pth
- Name: animal--2d_kpt_sview_rgb_img--topdown_heatmap--atrw--res101_atrw_256x256
  In Collection: resnet_atrw
  Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/atrw/res101_atrw_256x256.py
  Metadata:
    Training Data: ATRW
  Results:
  - Task: 2D Animal Keypoint Detection
    Dataset: ATRW
    Metrics:
      AP: 0.898
      AP50: 0.973
      AP75: 0.936
      AR: 0.927
      AR50: 0.985
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res101_atrw_256x256-da93f371_20210414.pth
- Name: animal--2d_kpt_sview_rgb_img--topdown_heatmap--atrw--res152_atrw_256x256
  In Collection: resnet_atrw
  Config: configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/atrw/res152_atrw_256x256.py
  Metadata:
    Training Data: ATRW
  Results:
  - Task: 2D Animal Keypoint Detection
    Dataset: ATRW
    Metrics:
      AP: 0.896
      AP50: 0.973
      AP75: 0.931
      AR: 0.927
      AR50: 0.985
  Weights: https://download.openmmlab.com/mmpose/animal/resnet/res152_atrw_256x256-2bb8e162_20210414.pth
