Collections:
- Metadata:
    Architecture:
    - SimpleBaseline2D (ECCV'2018)
    - ResNet (CVPR'2016)
  Name: body 2D Keypoint topdown_heatmap mhp
  Paper:
  - Title: Simple baselines for human pose estimation and tracking
    URL: http://openaccess.thecvf.com/content_ECCV_2018/html/Bin_Xiao_Simple_Baselines_for_ECCV_2018_paper.html
  - Title: Deep residual learning for image recognition
    URL: http://openaccess.thecvf.com/content_cvpr_2016/html/He_Deep_Residual_Learning_CVPR_2016_paper.html
  - Title: 'Understanding humans in crowded scenes: Deep nested adversarial learning
      and a new benchmark for multi-human parsing'
    URL: https://dl.acm.org/doi/abs/10.1145/3240508.3240509
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mhp/resnet_mhp.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mhp/res50_mhp_256x192.py
  In Collection: body 2D Keypoint topdown_heatmap mhp
  Metadata:
    Training Data: MHP (ACM MM'2018)
  Name: topdown_heatmap_res50_mhp_256x192
  Results:
  - Dataset: MHP (ACM MM'2018)
    Metrics:
      AP: 0.583
      AP@0.5: 0.897
      AP@0.75: 0.669
      AR: 0.636
      AR@0.5: 0.918
    Task: 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res50_mhp_256x192-28c5b818_20201229.pth
