Collections:
- Name: resnet_mhp
  Metadata:
    Architecture:
    - SimpleBaseline2D
    - ResNet
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mhp/resnet_mhp.md
  Paper:
  - Simple baselines for human pose estimation and tracking
  - Deep residual learning for image recognition
  - 'Understanding humans in crowded scenes: Deep nested adversarial learning and
    a new benchmark for multi-human parsing'
Models:
- Name: res50_mhp_256x192
  In Collection: resnet_mhp
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mhp/res50_mhp_256x192.py
  Metadata:
    Training Data: MHP
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: MHP
    Metrics:
      AP: 0.583
      AP50: 0.897
      AP75: 0.669
      AR: 0.636
      AR50: 0.918
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res50_mhp_256x192-28c5b818_20201229.pth
