Collections:
- Name: hrnet_aic
  Metadata:
    Architecture:
    - HRNet
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/aic/hrnet_aic.md
  Paper:
  - Deep high-resolution representation learning for human pose estimation
  - 'Ai challenger: A large-scale dataset for going deeper in image understanding'
Models:
- Name: hrnet_w32_aic_256x192
  In Collection: hrnet_aic
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/aic/hrnet_w32_aic_256x192.py
  Metadata:
    Training Data: AI Challenger
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: AI Challenger
    Metrics:
      AP: 0.323
      AP50: 0.762
      AP75: 0.219
      AR: 0.366
      AR50: 0.789
  Weights: https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_aic_256x192-30a4e465_20200826.pth
