Collections:
- Metadata:
    Architecture:
    - SimpleBaseline2D (ECCV'2018)
    - ResNet (CVPR'2016)
  Name: body 2D Keypoint topdown_heatmap aic
  Paper:
  - Title: Simple baselines for human pose estimation and tracking
    URL: http://openaccess.thecvf.com/content_ECCV_2018/html/Bin_Xiao_Simple_Baselines_for_ECCV_2018_paper.html
  - Title: Deep residual learning for image recognition
    URL: http://openaccess.thecvf.com/content_cvpr_2016/html/He_Deep_Residual_Learning_CVPR_2016_paper.html
  - Title: 'Ai challenger: A large-scale dataset for going deeper in image understanding'
    URL: https://arxiv.org/abs/1711.06475
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/aic/resnet_aic.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/aic/res101_aic_256x192.py
  In Collection: body 2D Keypoint topdown_heatmap aic
  Metadata:
    Training Data: AI Challenger (ArXiv'2017)
  Name: topdown_heatmap_res101_aic_256x192
  Results:
  - Dataset: AI Challenger (ArXiv'2017)
    Metrics:
      AP: 0.294
      AP@0.5: 0.736
      AP@0.75: 0.174
      AR: 0.337
      AR@0.5: 0.763
    Task: 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res101_aic_256x192-79b35445_20200826.pth
