Collections:
- Name: hourglass_coco
  Metadata:
    Architecture:
    - Hourglass
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hourglass_coco.md
  Paper:
  - Stacked hourglass networks for human pose estimation
  - 'Microsoft coco: Common objects in context'
Models:
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--coco--hourglass52_coco_256x256
  In Collection: hourglass_coco
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hourglass52_coco_256x256.py
  Metadata:
    Training Data: COCO
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: COCO
    Metrics:
      AP: 0.726
      AP50: 0.896
      AP75: 0.799
      AR: 0.78
      AR50: 0.934
  Weights: https://download.openmmlab.com/mmpose/top_down/hourglass/hourglass52_coco_256x256-4ec713ba_20200709.pth
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--coco--hourglass52_coco_384x384
  In Collection: hourglass_coco
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hourglass52_coco_384x384.py
  Metadata:
    Training Data: COCO
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: COCO
    Metrics:
      AP: 0.746
      AP50: 0.9
      AP75: 0.813
      AR: 0.797
      AR50: 0.939
  Weights: https://download.openmmlab.com/mmpose/top_down/hourglass/hourglass52_coco_384x384-be91ba2b_20200812.pth
