Collections:
- Name: hrnet_fp16_coco
  Metadata:
    Architecture:
    - HRNet
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_fp16_coco.md
  Paper:
  - Deep high-resolution representation learning for human pose estimation
  - Mixed precision training
  - 'Microsoft coco: Common objects in context'
Models:
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--coco--hrnet_w32_coco_256x192_fp16_dynamic
  In Collection: hrnet_fp16_coco
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_w32_coco_256x192_fp16_dynamic.py
  Metadata:
    Training Data: COCO
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: COCO
    Metrics:
      AP: 0.746
      AP@0.5: 0.905
      AP@0.75: 0.88
      AR: 0.8
      AR@0.5: 0.943
  Weights: hrnet_w32_coco_256x192_fp16_dynamic-290efc2e_20210430.pth
