Collections:
- Name: mspn_coco
  Metadata:
    Architecture:
    - MSPN
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/mspn_coco.md
  Paper:
  - Rethinking on Multi-Stage Networks for Human Pose Estimation
  - 'Microsoft coco: Common objects in context'
Models:
- Name: mspn50_coco_256x192
  In Collection: mspn_coco
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/mspn50_coco_256x192.py
  Metadata:
    Training Data: COCO
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: COCO
    Metrics:
      AP: 0.723
      AP50: 0.895
      AP75: 0.794
      AR: 0.788
      AR50: 0.933
  Weights: https://download.openmmlab.com/mmpose/top_down/mspn/mspn50_coco_256x192-8fbfb5d0_20201123.pth
- Name: 2xmspn50_coco_256x192
  In Collection: mspn_coco
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/2xmspn50_coco_256x192.py
  Metadata:
    Training Data: COCO
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: COCO
    Metrics:
      AP: 0.754
      AP50: 0.903
      AP75: 0.825
      AR: 0.815
      AR50: 0.941
  Weights: https://download.openmmlab.com/mmpose/top_down/mspn/2xmspn50_coco_256x192-c8765a5c_20201123.pth
- Name: 3xmspn50_coco_256x192
  In Collection: mspn_coco
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/3xmspn50_coco_256x192.py
  Metadata:
    Training Data: COCO
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: COCO
    Metrics:
      AP: 0.758
      AP50: 0.904
      AP75: 0.83
      AR: 0.821
      AR50: 0.943
  Weights: https://download.openmmlab.com/mmpose/top_down/mspn/3xmspn50_coco_256x192-e348f18e_20201123.pth
- Name: 4xmspn50_coco_256x192
  In Collection: mspn_coco
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/4xmspn50_coco_256x192.py
  Metadata:
    Training Data: COCO
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: COCO
    Metrics:
      AP: 0.764
      AP50: 0.906
      AP75: 0.835
      AR: 0.826
      AR50: 0.944
  Weights: https://download.openmmlab.com/mmpose/top_down/mspn/4xmspn50_coco_256x192-7b837afb_20201123.pth
