Collections:
- Metadata:
    Architecture:
    - SimpleBaseline2D (ECCV'2018)
    - ResNet (CVPR'2016)
  Name: body 2D Keypoint topdown_heatmap coco
  Paper:
  - Title: Simple baselines for human pose estimation and tracking
    URL: http://openaccess.thecvf.com/content_ECCV_2018/html/Bin_Xiao_Simple_Baselines_for_ECCV_2018_paper.html
  - Title: Deep residual learning for image recognition
    URL: http://openaccess.thecvf.com/content_cvpr_2016/html/He_Deep_Residual_Learning_CVPR_2016_paper.html
  - Title: Mixed precision training
    URL: https://arxiv.org/abs/1710.03740
  - Title: 'Microsoft coco: Common objects in context'
    URL: https://link.springer.com/chapter/10.1007/978-3-319-10602-1_48
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/resnet_fp16_coco.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/res50_coco_256x192_fp16_dynamic.py
  In Collection: body 2D Keypoint topdown_heatmap coco
  Metadata:
    Training Data: COCO (ECCV'2014)
  Name: topdown_heatmap_res50_coco_256x192_fp16_dynamic
  Results:
  - Dataset: COCO (ECCV'2014)
    Metrics:
      AP: 0.717
      AP@0.5: 0.898
      AP@0.75: 0.793
      AR: 0.772
      AR@0.5: 0.936
    Task: 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res50_coco_256x192_fp16_dynamic-6edb79f3_20210430.pth
