Collections:
- Name: resnet_fp16_coco
  Metadata:
    Architecture:
    - SimpleBaseline2D
    - ResNet
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/resnet_fp16_coco.md
  Paper:
  - Simple baselines for human pose estimation and tracking
  - Deep residual learning for image recognition
  - Mixed precision training
  - 'Microsoft coco: Common objects in context'
Models:
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--coco--res50_coco_256x192_fp16_dynamic
  In Collection: resnet_fp16_coco
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/res50_coco_256x192_fp16_dynamic.py
  Metadata:
    Training Data: COCO
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: COCO
    Metrics:
      AP: 0.717
      AP@0.5: 0.898
      AP@0.75: 0.793
      AR: 0.772
      AR@0.5: 0.936
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res50_coco_256x192_fp16_dynamic-6edb79f3_20210430.pth
