Collections:
- Name: seresnet_coco
  Metadata:
    Architecture:
    - SEResNet
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/seresnet_coco.md
  Paper:
  - Squeeze-and-excitation networks
  - 'Microsoft coco: Common objects in context'
Models:
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--coco--seresnet50_coco_256x192
  In Collection: seresnet_coco
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/seresnet50_coco_256x192.py
  Metadata:
    Training Data: COCO
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: COCO
    Metrics:
      AP: 0.728
      AP50: 0.9
      AP75: 0.809
      AR: 0.784
      AR50: 0.94
  Weights: https://download.openmmlab.com/mmpose/top_down/seresnet/seresnet50_coco_256x192-25058b66_20200727.pth
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--coco--seresnet50_coco_384x288
  In Collection: seresnet_coco
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/seresnet50_coco_384x288.py
  Metadata:
    Training Data: COCO
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: COCO
    Metrics:
      AP: 0.748
      AP50: 0.905
      AP75: 0.819
      AR: 0.799
      AR50: 0.941
  Weights: https://download.openmmlab.com/mmpose/top_down/seresnet/seresnet50_coco_384x288-bc0b7680_20200727.pth
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--coco--seresnet101_coco_256x192
  In Collection: seresnet_coco
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/seresnet101_coco_256x192.py
  Metadata:
    Training Data: COCO
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: COCO
    Metrics:
      AP: 0.734
      AP50: 0.904
      AP75: 0.815
      AR: 0.79
      AR50: 0.942
  Weights: https://download.openmmlab.com/mmpose/top_down/seresnet/seresnet101_coco_256x192-83f29c4d_20200727.pth
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--coco--seresnet101_coco_384x288
  In Collection: seresnet_coco
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/seresnet101_coco_384x288.py
  Metadata:
    Training Data: COCO
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: COCO
    Metrics:
      AP: 0.753
      AP50: 0.907
      AP75: 0.823
      AR: 0.805
      AR50: 0.943
  Weights: https://download.openmmlab.com/mmpose/top_down/seresnet/seresnet101_coco_384x288-48de1709_20200727.pth
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--coco--seresnet152_coco_256x192
  In Collection: seresnet_coco
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/seresnet152_coco_256x192.py
  Metadata:
    Training Data: COCO
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: COCO
    Metrics:
      AP: 0.73
      AP50: 0.899
      AP75: 0.81
      AR: 0.786
      AR50: 0.94
  Weights: https://download.openmmlab.com/mmpose/top_down/seresnet/seresnet152_coco_256x192-1c628d79_20200727.pth
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--coco--seresnet152_coco_384x288
  In Collection: seresnet_coco
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/seresnet152_coco_384x288.py
  Metadata:
    Training Data: COCO
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: COCO
    Metrics:
      AP: 0.753
      AP50: 0.906
      AP75: 0.823
      AR: 0.806
      AR50: 0.945
  Weights: https://download.openmmlab.com/mmpose/top_down/seresnet/seresnet152_coco_384x288-58b23ee8_20200727.pth
