Collections:
- Name: shufflenetv2_coco
  Metadata:
    Architecture:
    - ShufflenetV2
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/shufflenetv2_coco.md
  Paper:
  - 'Shufflenet v2: Practical guidelines for efficient cnn architecture design'
  - 'Microsoft coco: Common objects in context'
Models:
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--coco--shufflenetv2_coco_256x192
  In Collection: shufflenetv2_coco
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/shufflenetv2_coco_256x192.py
  Metadata:
    Training Data: COCO
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: COCO
    Metrics:
      AP: 0.599
      AP50: 0.854
      AP75: 0.663
      AR: 0.664
      AR50: 0.899
  Weights: https://download.openmmlab.com/mmpose/top_down/shufflenetv2/shufflenetv2_coco_256x192-0aba71c7_20200921.pth
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--coco--shufflenetv2_coco_384x288
  In Collection: shufflenetv2_coco
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/shufflenetv2_coco_384x288.py
  Metadata:
    Training Data: COCO
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: COCO
    Metrics:
      AP: 0.636
      AP50: 0.865
      AP75: 0.705
      AR: 0.697
      AR50: 0.909
  Weights: https://download.openmmlab.com/mmpose/top_down/shufflenetv2/shufflenetv2_coco_384x288-fb38ac3a_20200921.pth
