Collections:
- Metadata:
    Architecture:
    - DeepPose
    - ResNet
  Name: body 2D Keypoint deeppose mpii
  Paper:
  - Title: 'Deeppose: Human pose estimation via deep neural networks'
    URL: http://openaccess.thecvf.com/content_cvpr_2014/html/Toshev_DeepPose_Human_Pose_2014_CVPR_paper.html
  - Title: Deep residual learning for image recognition
    URL: http://openaccess.thecvf.com/content_cvpr_2016/html/He_Deep_Residual_Learning_CVPR_2016_paper.html
  - Title: '2D Human Pose Estimation: New Benchmark and State of the Art Analysis'
    URL: http://openaccess.thecvf.com/content_cvpr_2014/html/Andriluka_2D_Human_Pose_2014_CVPR_paper.html
  README: configs/body/2d_kpt_sview_rgb_img/deeppose/mpii/resnet_mpii.md
Models:
- Config: configs/body/2d_kpt_sview_rgb_img/deeppose/mpii/res50_mpii_256x256.py
  In Collection: body 2D Keypoint deeppose mpii
  Metadata:
    Training Data: MPII
  Name: deeppose_res50_mpii_256x256
  Results:
  - Dataset: MPII
    Metrics:
      Mean: 0.825
      Mean@0.1: 0.174
    Task: 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/deeppose/deeppose_res50_mpii_256x256-c63cd0b6_20210203.pth
- Config: configs/body/2d_kpt_sview_rgb_img/deeppose/mpii/res101_mpii_256x256.py
  In Collection: body 2D Keypoint deeppose mpii
  Metadata:
    Training Data: MPII
  Name: deeppose_res101_mpii_256x256
  Results:
  - Dataset: MPII
    Metrics:
      Mean: 0.841
      Mean@0.1: 0.193
    Task: 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/deeppose/deeppose_res101_mpii_256x256-87516a90_20210205.pth
- Config: configs/body/2d_kpt_sview_rgb_img/deeppose/mpii/res152_mpii_256x256.py
  In Collection: body 2D Keypoint deeppose mpii
  Metadata:
    Training Data: MPII
  Name: deeppose_res152_mpii_256x256
  Results:
  - Dataset: MPII
    Metrics:
      Mean: 0.85
      Mean@0.1: 0.198
    Task: 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/top_down/deeppose/deeppose_res152_mpii_256x256-15f5e6f9_20210205.pth
