Models:
- Config: configs/animal_2d_keypoint/topdown_heatmap/ak/td-hm_hrnet-w32_8xb64-210e_animalkingdom_P1-256x256.py
  In Collection: HRNet
  Metadata:
    Architecture: &id001
    - HRNet
    Training Data: AnimalKingdom_P1
  Name: td-hm_hrnet-w32_8xb64-210e_animalkingdom_P1-256x256
  Results:
  - Dataset: AnimalKingdom
    Metrics:
      PCK: 0.6272
    Task: Animal 2D Keypoint
  Weights: None
- Config: configs/animal_2d_keypoint/topdown_heatmap/ak/td-hm_hrnet-w32_8xb64-210e_animalkingdom_P2-256x256.py
  In Collection: HRNet
  Metadata:
    Architecture: *id001
    Training Data: AnimalKingdom_P2
  Name: td-hm_hrnet-w32_8xb64-210e_animalkingdom_P2-256x256
  Results:
  - Dataset: AnimalKingdom
    Metrics:
      PCK: 0.3774
    Task: Animal 2D Keypoint
  Weights: None
- Config: configs/animal_2d_keypoint/topdown_heatmap/ak/td-hm_hrnet-w32_8xb64-210e_animalkingdom_P3_amphibian-256x256.py
  In Collection: HRNet
  Metadata:
    Architecture: *id001
    Training Data: AnimalKingdom_P3_amphibian
  Name: td-hm_hrnet-w32_8xb64-210e_animalkingdom_P3_amphibian-256x256
  Results:
  - Dataset: AnimalKingdom
    Metrics:
      PCK: 0.5356
    Task: Animal 2D Keypoint
  Weights: None
- Config: configs/animal_2d_keypoint/topdown_heatmap/ak/td-hm_hrnet-w32_8xb64-210e_animalkingdom_P3_bird-256x256.py
  In Collection: HRNet
  Metadata:
    Architecture: *id001
    Training Data: AnimalKingdom_P3_bird
  Name: td-hm_hrnet-w32_8xb64-210e_animalkingdom_P3_bird-256x256
  Results:
  - Dataset: AnimalKingdom
    Metrics:
      PCK: 0.7679
    Task: Animal 2D Keypoint
  Weights: None
- Config: configs/animal_2d_keypoint/topdown_heatmap/ak/td-hm_hrnet-w32_8xb64-210e_animalkingdom_P3_fish-256x256.py
  In Collection: HRNet
  Metadata:
    Architecture: *id001
    Training Data: AnimalKingdom_P3_fish
  Name: td-hm_hrnet-w32_8xb64-210e_animalkingdom_P3_fish-256x256
  Results:
  - Dataset: AnimalKingdom
    Metrics:
      PCK: 0.643
    Task: Animal 2D Keypoint
  Weights: None
- Config: configs/animal_2d_keypoint/topdown_heatmap/ak/td-hm_hrnet-w32_8xb64-210e_animalkingdom_P3_mammal-256x256.py
  In Collection: HRNet
  Metadata:
    Architecture: *id001
    Training Data: AnimalKingdom_P3_mammal
  Name: td-hm_hrnet-w32_8xb64-210e_animalkingdom_P3_mammal-256x256
  Results:
  - Dataset: AnimalKingdom
    Metrics:
      PCK: 0.5756
    Task: Animal 2D Keypoint
  Weights: None
- Config: configs/animal_2d_keypoint/topdown_heatmap/ak/td-hm_hrnet-w32_8xb64-210e_animalkingdom_P3_reptile-256x256.py
  In Collection: HRNet
  Metadata:
    Architecture: *id001
    Training Data: AnimalKingdom_P3_reptile
  Name: td-hm_hrnet-w32_8xb64-210e_animalkingdom_P3_reptile-256x256
  Results:
  - Dataset: AnimalKingdom
    Metrics:
      PCK: 0.5
    Task: Animal 2D Keypoint
  Weights: None
