Collections:
- Name: resnet_mpii_trb
  Metadata:
    Architecture:
    - SimpleBaseline2D
    - ResNet
  README: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii_trb/resnet_mpii_trb.md
  Paper:
  - Simple baselines for human pose estimation and tracking
  - Deep residual learning for image recognition
  - 'TRB: A Novel Triplet Representation for Understanding 2D Human Body'
Models:
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--mpii_trb--res50_mpii_trb_256x256
  In Collection: resnet_mpii_trb
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii_trb/res50_mpii_trb_256x256.py
  Metadata:
    Training Data: MPII-TRB
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: MPII-TRB
    Metrics:
      Skeleton Acc: 0.887
      Contour Acc: 0.858
      Mean Acc: 0.868
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res50_mpii_trb_256x256-896036b8_20200812.pth
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--mpii_trb--res101_mpii_trb_256x256
  In Collection: resnet_mpii_trb
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii_trb/res101_mpii_trb_256x256.py
  Metadata:
    Training Data: MPII-TRB
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: MPII-TRB
    Metrics:
      Skeleton Acc: 0.89
      Contour Acc: 0.863
      Mean Acc: 0.873
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res101_mpii_trb_256x256-cfad2f05_20200812.pth
- Name: body--2d_kpt_sview_rgb_img--topdown_heatmap--mpii_trb--res152_mpii_trb_256x256
  In Collection: resnet_mpii_trb
  Config: configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii_trb/res152_mpii_trb_256x256.py
  Metadata:
    Training Data: MPII-TRB
  Results:
  - Task: Image-based Human Body 2D Pose Estimation
    Dataset: MPII-TRB
    Metrics:
      Skeleton Acc: 0.897
      Contour Acc: 0.868
      Mean Acc: 0.879
  Weights: https://download.openmmlab.com/mmpose/top_down/resnet/res152_mpii_trb_256x256-dd369ce6_20200812.pth
