Collections:
- Metadata:
    Architecture:
    - HRNetv2 (TPAMI'2019)
  Name: hand 2D Keypoint topdown_heatmap panoptic2d
  Paper:
  - Title: Deep High-Resolution Representation Learning for Visual Recognition
    URL: https://ieeexplore.ieee.org/abstract/document/9052469/
  - Title: Hand keypoint detection in single images using multiview bootstrapping
    URL: http://openaccess.thecvf.com/content_cvpr_2017/html/Simon_Hand_Keypoint_Detection_CVPR_2017_paper.html
  README: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/panoptic2d/hrnetv2_panoptic2d.md
Models:
- Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/panoptic2d/hrnetv2_w18_panoptic_256x256.py
  In Collection: hand 2D Keypoint topdown_heatmap panoptic2d
  Metadata:
    Training Data: CMU Panoptic HandDB (CVPR'2017)
  Name: topdown_heatmap_hrnetv2_w18_panoptic_256x256
  Results:
  - Dataset: CMU Panoptic HandDB (CVPR'2017)
    Metrics:
      AUC: 0.744
      EPE: 7.79
      PCKh@0.7: 0.999
    Task: 2D Keypoint
  Weights: https://download.openmmlab.com/mmpose/hand/hrnetv2/hrnetv2_w18_panoptic_256x256-53b12345_20210330.pth
