Collections:
- Name: hrnetv2_udp_panoptic2d
  Metadata:
    Architecture:
    - HRNetv2
    - UDP
  README: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/panoptic2d/hrnetv2_udp_panoptic2d.md
  Paper:
  - Deep High-Resolution Representation Learning for Visual Recognition
  - 'The Devil Is in the Details: Delving Into Unbiased Data Processing for Human
    Pose Estimation'
  - Hand keypoint detection in single images using multiview bootstrapping
Models:
- Name: hrnetv2_w18_panoptic_256x256_udp
  In Collection: hrnetv2_udp_panoptic2d
  Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/panoptic2d/hrnetv2_w18_panoptic_256x256_udp.py
  Metadata:
    Training Data: CMU Panoptic HandDB
  Results:
  - Task: 2D Hand Pose Estimation
    Dataset: CMU Panoptic HandDB
    Metrics:
      PCKh@0.7: 0.998
      AUC: 0.742
      EPE: 7.84
  Weights: https://download.openmmlab.com/mmpose/hand/udp/hrnetv2_w18_panoptic_256x256_udp-f9e15948_20210330.pth
