Collections:
- Name: resnet_panoptic2d
  Metadata:
    Architecture:
    - SimpleBaseline2D
    - ResNet
  README: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/panoptic2d/resnet_panoptic2d.md
  Paper:
  - Simple baselines for human pose estimation and tracking
  - Deep residual learning for image recognition
  - Hand keypoint detection in single images using multiview bootstrapping
Models:
- Name: res50_panoptic_256x256
  In Collection: resnet_panoptic2d
  Config: configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/panoptic2d/res50_panoptic_256x256.py
  Metadata:
    Training Data: CMU Panoptic HandDB
  Results:
  - Task: 2D Hand Pose Estimation
    Dataset: CMU Panoptic HandDB
    Metrics:
      PCKh@0.7: 0.999
      AUC: 0.713
      EPE: 9.0
  Weights: https://download.openmmlab.com/mmpose/hand/resnet/res50_panoptic_256x256-4eafc561_20210330.pth
